### ISSUE TITLE
Use a configuration file for Read the Docs

### ISSUE THREAD

**Issue by stsewd** [theacodes/nox#102]
I notice this comment here https://github.com/theacodes/nox/blob/c64cc8e43ca41ef1e9eae71073f0b696538e3dc3/nox.py#L65

If you want to install using pip on rtd, you can, but you need to use a configuration file https://docs.readthedocs.io/en/latest/yaml-config.html#python-pip-install

**Comment by theacodes** [comment]
Yep, we could. If you want you're welcome to send a PR for it.
