### ISSUE TITLE
Use `black` for code formatting

### ISSUE THREAD

**Issue by dhermes** [theacodes/nox#114]
Fancy new [code formatter][1]. I use the following on my projects:

```
$ virtualenv venv
$ venv/bin/pip install git+https://github.com/ambv/black
$ venv/bin/black --line-length=79 $(git ls-files '*.py') 
```

[1]: https://github.com/ambv/black

**Comment by theacodes** [comment]
I'm 100% in favor of this.

**Comment by dhermes** [comment]
Nice one! @theacodes The [`blacken` session][1] isn't very future proof. Are you opposed to using 
`$(git ls-files '*.py')` to make sure all source files get blackened?

[1]: https://github.com/theacodes/nox/blob/fe5276969d3073faeeb4bb1e4803cd9e32960415/noxfile.py#L45-L48

**Comment by theacodes** [comment]
@dhermes I'm not opposed, but there's only two top-level files that I care about formatting right now.

**Comment by dhermes** [comment]
OK. We can revisit if needed. SGTM.

**Comment by theacodes** [comment]
Thank you for your attention to detail. :)
