### ISSUE TITLE
Tox to nox template needs to be updated

### ISSUE THREAD

**Issue by stsewd** [theacodes/nox#116]
I haven't look at the file in the detail, but there are lines that still use `session.interpreter`.

https://github.com/theacodes/nox/blob/master/nox/tox_to_nox.jinja2

**Comment by dhermes** [comment]
@theacodes maybe add that `@property` after all? Or slots?

**Comment by theacodes** [comment]
> Or slots?

Slots for sure.

**Comment by theacodes** [comment]
Closed by 24cea2bb
