### ISSUE TITLE
reuse_existing should check the interpreter

### ISSUE THREAD

**Issue by dhermes** [theacodes/nox#123]
If `reuse_existing=True` when creating a `Virtualenv`, but the interpreter has changed, then the environment should still be re-created.

**Comment by theacodes** [comment]
Interesting, wouldn't that change the name of the virtualenv folder?

**Comment by dhermes** [comment]
@theacodes I'm not 100% sure, but I think "not always" is the answer.

**Comment by theacodes** [comment]
Cool, makes sense for us to check it then.

**Comment by theacodes** [comment]
I'm not 100% how to do this yet. We don't ever know the full path to the interpreter, we just figure out enough info to get virtualenv to figure it out. I could try invoking the interpreter.

**Comment by dhermes** [comment]
Yes. You can get the actual interpreter via:

```python
original = session.run("python", "-c", "import sys; print(sys.real_prefix)")
```

**Comment by theacodes** [comment]
Invoking the interpreter doesn't quite get me any closer. We could invoke our resolved interpreter and invoke the one in the virtualenv and compare. Still not 100% sure on that.

**Comment by dhermes** [comment]
Yes that's what you want to do.

**Comment by theacodes** [comment]
From #231, we should also test the *type* of environment.
