### ISSUE TITLE
`nox` uses `PATH` to find executables

### ISSUE THREAD

**Issue by dhermes** [theacodes/nox#130]
This is a bit `tox`-like to suggest, so feel free to reject.

I was recently migrating my Pelican blog from a `Makefile` to a `noxfile`. I had `pelican` installed in a few of my base environments, but forgot to install it into the virtual environment. However, the sessions ran just fine because they referenced the `pelican` executable on my `${PATH}` even though none existed in the `virtualenv`.

**Comment by theacodes** [comment]
hrm. This is tricky. I never was a fan of tox being onerous about stuff needing to be in the virtualenv, but I can definitely see why its useful. How can we handle this gracefully?

**Comment by dhermes** [comment]
I've been using `os.path.join(session.bin, "pelican")` to be explicit. I'm not sure what the right move is, you could have both options supported (i.e. one with an empty `PATH` and one with `PATH` passed down from the calling shell). Then it's up to you to decide which one should be the default.

**Comment by theacodes** [comment]
yeah it's tricky. We could do something like:

```
nox.run(..., external=True)
```

or flip-side:

```
nox.run(..., virtualenv_only=True)
```

We could also have a flag, such as `--warn-on-external-tools` / `--no-warn-on-external-tools` or something.

**Comment by dhermes** [comment]
ISTM that `external=True` (i.e. opt-**in** to non-virtualenv scripts) should be the default. That's just 1 vote though.

**Comment by theacodes** [comment]
So by default you can only use tools that are *in* the virtualenv, otherwise, we error?

**Comment by theacodes** [comment]
Hrm, what is your take @lukesneeringer?

I am in favor of this with one caveat - by default we *warn* but a flag could be passed to error instead.
