### ISSUE TITLE
Some internal links in docs have low color contrast

### ISSUE THREAD

**Issue by busunkim96** [theacodes/nox#131]
Some internal reference links in https://nox.readthedocs.io/ have similarly colored text and backgrounds.

See https://nox.readthedocs.io/en/stable/config.html#module-nox.sessions
![en9pwt8ygme](https://user-images.githubusercontent.com/8822365/45120505-2949d680-b113-11e8-8f70-aa30be735a01.png)

**Comment by theacodes** [comment]
Fixed this in the last doc stylesheet update. Thanks for reporting!
