### ISSUE TITLE
CTRL-C always results in an error

### ISSUE THREAD

**Issue by dhermes** [theacodes/nox#139]
If `nox -s foo` encounters a `KeyboardInterrupt` but the currently running script catches it and handles it gracefully, `nox` will still report a failure. For example:

```
$ nox -s app -r
nox > Running session app-3.7
nox > Re-using existing virtualenv at .../.nox/app-3-7.
nox > pip install --upgrade --requirement .../requirements/app.txt
nox > cd .../src
nox > python -m flask run
 * Serving Flask app "app.py" (lazy loading)
...
127.0.0.1 - - [20/Sep/2018 15:43:27] "GET /foo HTTP/1.1" 200 -
127.0.0.1 - - [20/Sep/2018 15:43:31] "GET /bar HTTP/1.1" 200 -
127.0.0.1 - - [20/Sep/2018 15:43:33] "GET /baz HTTP/1.1" 404 -
^Cnox > Interrupted...
nox > Session app-3.7 interrupted.
$ echo $?
130
```

However, if the same application runs outside of `nox` there is no error (i.e. `flask` exits gracefully):

```
$ cd src/
$ FLASK_APP=app.py ../.nox/app-3-7/bin/python -m flask run
 * Serving Flask app "app.py"
...
127.0.0.1 - - [20/Sep/2018 15:46:09] "GET /foo HTTP/1.1" 200 -
127.0.0.1 - - [20/Sep/2018 15:46:12] "GET /baz HTTP/1.1" 404 -
127.0.0.1 - - [20/Sep/2018 15:46:13] "GET /bar HTTP/1.1" 200 -
^C
$ echo $?
0
$ cd ..
```

What should the correct `nox` behavior be here?

**Comment by theacodes** [comment]
Nox doesn't pass the signal to the subprocess, it just kills it outright. Maybe we should fix that.

**Comment by pradyunsg** [comment]
FWIW, I have a session that might be affected by this:

```py
@nox.session
def run(session):
    session.install("pelican")

    cmd = [
        "python",
        "-m",
        "http.server",
        str(CONFIGURATION["dev_port"]),
        "-d",
        CONFIGURATION["output_path"],
    ]
    # NOTE: A bare Popen() results in a child being spawned.
    #       As of nox 2018.10.17, this child gets killed when the process ends.
    session.log(" ".join(cmd) + " (background)")
    subprocess.Popen(cmd)

    # -r means this process rebuilds until it receives a ^C or gets killed.
    session.run("pelican", "-r", "-d", "-s", CONFIGURATION["dev"], "src")
```

TBH, this is more of a generic automation thing that I'm using nox for than just testing but I think it's pretty awesome that nox is flexible enough to be able to do this. :)

**Comment by cjolowicz** [comment]
Just adding another use case here...

This behavior also appears to break `pytest --pdb`. For example, when debugging something like intermittent deadlocks, ^C terminates pytest instead of dropping you into pdb.

**Comment by theacodes** [comment]
This could resolved by modifying [this code](https://github.com/theacodes/nox/blob/211702da6112cf390b50b807ff1ebdaf844f73e2/nox/popen.py#L59-L62) to pass an interrupt signal to the child process instead of just killing it outright. We should, however, make sure to have some reasonable timeout and kill the child process if it hangs.
