### ISSUE TITLE
Allow specifying command-line parameters in `noxfile`

### ISSUE THREAD

**Issue by theacodes** [theacodes/nox#141]
Related #133, #40, #135.

Noxfiles should be able to specify *some* of the command-line args in the noxfile, for example:

```python
import nox

nox.options.envdir = ".cache"
nox.options.sessions = ["tests", "lint"]

...
```

Command-line args should *override* these "defaults" in the noxfile.

**Comment by moshez** [comment]
I'm happy to take this on. I've been looking for an excuse to learn about nox internals for a while :)

**Comment by theacodes** [comment]
@moshez go for it! holler if you run into any trouble or have any questions.

**Comment by theacodes** [comment]
The exact list of flags that should be specifiable in the noxfile are:

```
  --envdir ENVDIR       Directory where nox will store virtualenvs.
  -s [SESSIONS [SESSIONS ...]], -e [SESSIONS [SESSIONS ...]], --sessions [SESSIONS [SESSIONS ...]]
                        Which sessions to run, by default, all sessions will
                        run.
  -k KEYWORDS, --keywords KEYWORDS
                        Only run sessions that match the given expression.
  -r, --reuse-existing-virtualenvs
  -x, --stop-on-first-error
  --error-on-missing-interpreters
  --report REPORT
  --nocolor
  --forcecolor
```

Basically, everything but `--noxfile` can be specified in the `noxfile`.
