### ISSUE TITLE
Write a guide on how to use Nox with Travis/AppVeyor

### ISSUE THREAD

**Issue by theacodes** [theacodes/nox#149]

**Comment by schuderer** [comment]
I was looking for this and actually got quite far using `nox`' own .travis.yml as a basis I extended. So this could possibly act as a stub for the time being. I am also using `pipenv`, though, and the getting `nox`, `pipenv` (no requirements.txt) and CI tooling to work together is an ... interesting ... challenge. :)

**Comment by theacodes** [comment]
If you're willing to link to your project we'd love to have that as a reference for whoever writes this.

**Comment by schuderer** [comment]
Absolutely! https://github.com/schuderer/mllaunchpad. (when suggesting something to use as a stub, I meant nox' travis file, not mine, but the more examples the better I assume. It comes with a huuge caveat, though: I regard myself as a novice at python, particularly when it comes to creating and maintaining distributions. So the way I tackle things might work, more or less, but has a high chance of being clumsy (like having virtual environments inside virtual environments on Travis, installing more dependencies on Travis than strictly needed to avoid specifying the same dependencies in several places, and so on).

PS: I found nox when looking at PyCon videos about testing/packaging. Really nice talk! I also want to try to use the noxfile as a cross-platform way to unify (and replace) as many as possible of those build-related scripts/makefiles that I have now.

**Comment by theacodes** [comment]
Glad you enjoyed the talk. We're all novices! If you'd like to try sending
a PR for this I'm happy to help. :)

**Comment by jayvdb** [comment]
I did a bit of custom logic for Travis at https://github.com/pipxproject/pipx/pull/236

**Comment by MartinThoma** [comment]
It would be nice to have something like `nox-travis`, similar to [`tox-travis`](https://github.com/tox-dev/tox-travis)

**Comment by theacodes** [comment]
That would be rad! I don't use Travis anymore but I would love to see
someone else do it and I'm happy to help in any way I can.

**Comment by MartinThoma** [comment]
@theacodes What do you use instead of travis?

**Comment by theacodes** [comment]
Mostly GitHub actions, except on this repo because I haven't migrated it
yet 😶

**Comment by theacodes** [comment]
Travis & AppVeyor have fallen out of favor, so I'm closing this for now.
