### ISSUE TITLE
Run session with an unregistered interpreter 

### ISSUE THREAD

**Issue by stsewd** [theacodes/nox#158]
```python

@nox.session(python=['3.5', '3.6'])
def test():
    ...
```

```bash
$ nox -s test-3.7
nox> Warning: running session with custom interpreter
...
```

Raised in https://github.com/theacodes/nox/issues/95

**Comment by pradyunsg** [comment]
Noting here that pip's use cases would benefit from this.

We frequently have folks who's want to run pip on a not-in-the-list interpreter, to make sure things work on other platforms.

**Comment by crwilcox** [comment]
@pradyunsg I am going to take some time tomorrow and see about this.
