### ISSUE TITLE
List all sections when a list of sections is set using nox.options

### ISSUE THREAD

**Issue by pradyunsg** [theacodes/nox#161]
**Describe the bug**
Setting `nox.options.sessions` results in `nox -l` only those sections, not all the sections.

**How to reproduce**
Create a `noxfile.py` with 3 sessions (format, tests, docs) and set `nox.options.sessions = ["format"]`, then run `nox -l`:

```
Available sessions:
* format
```

**Expected behavior**
It would be better if `nox -l` would actually list all the sessions.

---

Related Feature Request: The sessions that are run by default be marked with a `*` while the others won't have a bullet:

```
Available sessions:
* format
  tests
  docs
```

**Comment by theacodes** [comment]
Good catch. Filtering happens before listing. I'd like to keep that behavior for the `-k` argument but not for the `-s` argument.

**Comment by pradyunsg** [comment]
The -s docstring also needs to be updated for the change in behavior possible via the options attribute?

It currently says that all sessions are run when -s is not given, but currently that is not the case anymore.

**Comment by theacodes** [comment]
Yeah, good call.
