### ISSUE TITLE
[Help Wanted] - Runnng nox fails with a Syntax Error: invalid syntax - error

### ISSUE THREAD

**Issue by naveenwashere** [theacodes/nox#162]
Hello everyone,

Thanks in advance for looking into this issue. I'm a first time user of nox and I'm trying to run some tests on a project that uses nox (which is the `google-cloud-python` project). I installed nox using `pip` and ran the unit tests as instructed on google's project, but always end up with the following error, but I'm not sure what's wrong:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/nox", line 7, in <module>
    from nox.__main__ import main
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nox/__main__.py", line 155
    print(dist.version, file=sys.stderr)
                            ^
SyntaxError: invalid syntax
```

I apologize if this is a very silly error or if there's a fundamental setup issue on my laptop. Here are the steps that I followed:
* Clone `google-cloud-python` project
* Create a virtual virtual environmene using `virtualenv`
* Install `nox` using `pip install nox`
* Run the following command to run the tests in the repo: `nox -f bigtable/noxfile.py -s unit-2.7`

This results in the error trace I've posted above, every time. I installed all other requirements that the project requires based on their `docs/requirements.txt` file, but always end up in this issue.

Development Environment details:
- Python 2.7.13
- MacOS Mojave

Please let me know if any more info is required from me.

Thanks,
Naveen

**Comment by SethMichaelLarson** [comment]
Nox is Python 3.5 only.

**Comment by theacodes** [comment]
Yep. Nox can be used to test any version of Python, but Nox itself must be installed under 3.5+.
