### ISSUE TITLE
Alternate Nox config

### ISSUE THREAD

**Issue by s0undt3ch** [theacodes/nox#165]
Been looking at nox and I believe it suites one of our projects needs which is currently using tox, though I would prefer to have more leeway, hence considering Nox.

I'd prefer not to have a `noxfile.py` file on the root of our repo.

Would you be willing to accept a PR which still defaults to `noxfile.py` but can look for alternative paths?

At first I though about `.nox/noxfile.py` but I guess nuking the `.nox` directory to delete the virtualenvs is something users do a lot, so, perhaps:

* `.noxdir/conf.py` for linux, ,`_noxdir/conf.py` for windows?
* `.noxconf/conf.py`?
I guess I would even be ok with a `.noxfile` without the `.py` extension.

Of course, the purpose is not having to pass the alternate config on the nox CLI.

Look at `setup.cfg` and/or `pyproject.toml` for a nox section where we can then define the path to the `noxfile.py`?

Anyway, totally open for the alternative, but I wanted to ask before I set out to add support and it just gets rejected.

**Comment by theacodes** [comment]
Hi @s0undt3ch, Nox already lets you specify an alternative noxfile using the `-f` flag which I think is honestly enough. I'm a bit hesitant to make nox try to read setup.cfg or pyproject.toml (especially the latter, as I don't want to pull in another dependency), but I can be convinced otherwise.

**Comment by s0undt3ch** [comment]
Our team has agreed to give Nox a go.
The `noxfile.py` still itches me :)

I know that nox allows you to pass alternate configs through the CLI, but that's extra typing for our devs, worse our community.

Adding another dependency is also not my desire.

Would you be comfortable with any of the following options:
1. `.noxfile`
2. `.noxfile.py`
3. `.noxconf/noxfile.py`

The idea here would be, if nothing is passed on the CLI, then look for the existing default config `noxfile.py` and if this one is not found look for one of the above alternatives.

**Comment by theacodes** [comment]
Hrm, I'm open to the idea but I'm a bit concerned here. Several other tools don't really have any accommodation for this.

Tox supports using `tox.ini`, `pyproject.toml`, and `setup.cfg` presumably to better interop with packaging tools since it's very much geared towards packages. However, there's no alternatives to spelling the standalone config file.

PyTest (which is a direct influence on Nox, moreso than Tox), recursivsely looks for `pytest.ini`, `tox.ini`, or `setup.cfg`. But again, there's no alternative spellings for the standalone config.

**Comment by s0undt3ch** [comment]
How about we follow pytest's choices and support a plain ini file, `nox.ini` which would have a `nox` section where we could set, at least(or even only), the CLI options to pass to nox?

https://docs.pytest.org/en/latest/customize.html#adding-default-options

**Comment by s0undt3ch** [comment]
That way we could "hide" the `noxfile.py` from the top dir and still have nox working...

**Comment by theacodes** [comment]
Hm, that's antithetical to Nox's approach. Python-is-configuration here, not text files. For example, Nox already has a provision to specify command-line parameters in the `noxfile.py` file. Introducing ini files complicates Nox itself, our configuration story, and our rationalization. It's basically a non-starter for me.

**Comment by s0undt3ch** [comment]
Then an alternate `noxfile.py` name, you pick, something that doesn't suggest it's a script to run.
Don't worry about the implementation, I'll submit a PR.

**Comment by theacodes** [comment]
But it *is* a script. Is your primary concern with the `.py` extension? What problem are you attempting to avoid by introducing an alternative name?

**Comment by s0undt3ch** [comment]
It is a script, but it's not meant to be executed directly, `python noxfile.py`, right?
I would like it be less visible, `.noxfile.py` for example.

**Comment by theacodes** [comment]
Hrm, I don't like the idea of the configuration file being hidden.

Just because a script isn't meant to be executed directly by the interpreter doesn't mean it isn't still a Python script.

**Comment by s0undt3ch** [comment]
I'm not talking about changing the existing name, so your concerns about it being hidden are good.
I'm talking about providing an alternate name if the default one isn't found.

**Comment by theacodes** [comment]
still, I find the idea of a hidden file being used for this sort of configuration alarming. How will other people who use your codebase know that Nox is in play? Won't it be surprising when you say "use Nox" but they don't see a configuration file by default in most OSes? I suppose there is some precedence for this for things like `.travis.yml` so I'm not totally opposed.

I'm still unsure what problem we're trying to solve by having alternative names at all. What problem does `noxfile.py` cause right now? How does re-naming/adding additional names help that?

**Comment by s0undt3ch** [comment]
I've explained it.
It's too visible for a config file(yes, a script, but it's about nox config and behavior) and we already have a lot of _visible_ files on the repo top level directory, I'd prefer not to add a new one.
`noxfile.py` at the top level suggests similar behavior as `setup.py`, run it.

**Comment by s0undt3ch** [comment]
And the new name is not hidden, _per se_, we just get used to filter out, unless looking for it, files which start with a dot.

**Comment by theacodes** [comment]
Curious to get @lukesneeringer and @dhermes's opinion here: How would y'all feel if we looked for both `noxfile.py` and `.noxfile.py`?

**Comment by dhermes** [comment]
I don't think it'd be that big of a deal to support both, but I also don't think it's needed. Opening up to say "yes" to little requests like this expands the complexity drip-by-drip for little gain.

**Comment by theacodes** [comment]
Yeah, I'm remembering "Yes is forever, no is temporary".

**Comment by s0undt3ch** [comment]
Hmm, not looking good on my end :smile:

**Comment by waynew** [comment]
For what it's worth, you could just explicitly state that `noxfile.py` and `.noxfile.py` are it.

Or alternatively, and more complex, would it be possible to provide a nox hook in the `noxfile.py`, e.g. `nox.init(__name__)` or something, and if that `__name__ == '__main__'` you know it's been run as `python noxfile.py` so either a) you can say "don't do that, you're doing it wrong" and `sys.exit(1)` or b) just make it do whatever nox does by default?

I mean, it would require people to do something conventional - but that option does take care of @s0undt3ch 's objection, that people might just run the script. There's still the preference for not adding *more* files to the toplevel, but if you're reticent to also seek for the dotfile version of the .py script, that might be a reasonable alternative.

**Comment by dhermes** [comment]
> objection, that people might just run the script

It seems Python already supports this case:

```python
if __name__ == '__main__':
    raise NotImplementedError
```

**Comment by theacodes** [comment]
I'd be happy to make `import nox` exit if the noxfile is ran directly.

**Comment by s0undt3ch** [comment]
My main reason for this issue wouldn't be solved.
I still don't like the `noxfile.py` suggested visibility.

But, _you can't always get what you want..._
... and my arguments weren't enough to make a point, so, I'll just suck it up :)

**Comment by theacodes** [comment]
I'm going to close this for now, but by no means do I think this conversation is over. I'm happy to keep discussing, I just also like to keep the issue tracker limited to actionable issues.

**Comment by vaneseltine** [comment]
> I'd be happy to make `import nox` exit if the noxfile is ran directly.

I'd like to recommend against that... I like being able to add a little utility to a noxfile, e.g., 

```
if __name__ == "__main__":
    print(f"Pythons supported: {supported_pythons()}")
    pypi_report()
    print(f"Invoke {__file__} by running Nox.")
```

**Comment by Abhijeet-Linux** [comment]
Sir, I am getting a little bit problem during installing nox in kali linux.
Problem:-  Noxfile /home/noxfile.py not found.

**Comment by cjolowicz** [comment]
Hi @Abhijeet-Linux you need to invoke Nox from the directory containing your noxfile.py.

If you have further questions, could you please open a new issue? Thanks :)
