### ISSUE TITLE
Update nox-automation to point to nox

### ISSUE THREAD

**Issue by alixhami** [theacodes/nox#166]
**Describe the bug**
I used to have nox-automation installed, then the package changed at some point and I started getting confusing errors until I finally realized I needed to uninstall nox-automation and install nox. It would be nice to have the old package name somehow point to the new package, or have a deprecation warning when nox-automation is installed or updated.

**Comment by theacodes** [comment]
I should publish an empty nox-automation package that just depends on `nox`.

**Comment by theacodes** [comment]
Done https://pypi.org/project/nox-automation/

**Comment by theacodes** [comment]
For posterity, the redirect package's code is located here: https://github.com/theacodes/nox/tree/nox-automation-redirect
