### ISSUE TITLE
Include changelog in docs

### ISSUE THREAD

**Issue by stsewd** [theacodes/nox#169]
**How would this feature be useful?**

Right now the changelog lives only in the repo.
Would be nice to have it in http://nox.thea.codes/en/stable/changelog.html where it's more visible.

We could just link from there to the file in the repo or convert the file from markdown to rst, so it would be rendered in the docs page.

**Comment by theacodes** [comment]
This is a great idea. I'm all for it.

**Comment by stsewd** [comment]
Are you :+1:  on changing from markdown to rst?

**Comment by dhermes** [comment]
May be useful to use https://pypi.org/project/towncrier/

Also the Changelog approach from bezier may be worth a look: https://github.com/dhermes/bezier/tree/master/docs/releases

**Comment by theacodes** [comment]
I'm not super keen on towncrier.
