### ISSUE TITLE
Log pip install command output

### ISSUE THREAD

**Issue by s0undt3ch** [theacodes/nox#173]
**How would this feature be useful?**
Besides making it similar to tox(allowing for a smoother transition to nox), it's often useful in case of issues to, even though installing the requirements didn't fail, know which versions were actually installed.

**Describe the solution you'd like**
One solution would be do always show that output.
The other solution would be to add a `--verbose` boolean flag which, when passed, would additionally log the output of the pip install command (https://github.com/s0undt3ch/nox/commit/b5049abd13682a4e8b10fb67c413de53645cd1b4)

**Describe alternatives you've considered**
The only alternative is "patching" nox or submitting a PR to fix/enhance nox.

**Comment by s0undt3ch** [comment]
This is particularly useful in CI contexts

**Comment by theacodes** [comment]
Don't we already show that output if anything goes wrong?

I'm -1 for showing pip output always by default, it's incredibly noisy.

**Comment by s0undt3ch** [comment]
Only if something goes wrong, yes, if nothing goes wrong, we can never get that output.
I'm also -1 with always showing that output, but the additional flag to show the output of all commands? I'd go for that and that's what I did on a branch which I link above.
If that's accepted, I'll submit a PR.

**Comment by theacodes** [comment]
Yeah since it's plumbed through the normal run thing we should let users
set that flag. Sounds good.

**Comment by s0undt3ch** [comment]
Ok, I'll submit a PR.

**Comment by erinwild-rubikloud** [comment]
See the comment I left on your PR for a way to achieve this currently:

> It's already possible to override the silent flag in session.install (see #157). If the desired outcome is conditional reporting particularly in a CI context, the function in the noxfile could potentially handle this via extra arguments.
> 
> For example, `nox -s tests -- verbose` when additional verbosity is desired:
> 
> ```python
> @nox.session(python='3.7')
> def tests(session):
>     verbosity = True if 'verbose' in session.posargs else False
>     session.install('numpy', silent=verbosity)
> ```

**Comment by vaneseltine** [comment]
Was this closed by https://github.com/theacodes/nox/pull/174?

**Comment by theacodes** [comment]
Yeah I think so.
