### ISSUE TITLE
Consider using semantic versioning

### ISSUE THREAD

**Issue by richin13** [theacodes/nox#175]
**How would this feature be useful?**

It'll enable better integration with new tools like [poetry](https://poetry.eustace.io/) that heavily rely on semantic versioning

**Describe the solution you'd like**

Future releases of `nox` are versioned using the [Semantic](https://semver.org/) spec

**Describe alternatives you've considered**

Not applicable

**Comment by theacodes** [comment]
Nox intentionally switched to Calver when we dropped Python 2 support. Nox is primarily a tool and not a library (although it has a very small interface used for the noxfile), I do not think semver conveys any sort of useful versioning info for Nox.
