### ISSUE TITLE
Promote contributors to maintainers

### ISSUE THREAD

**Issue by theacodes** [theacodes/nox#188]
Nox has grown so much with significant contributions from people other than me.

I would very much like to promote more people to maintainers on this project. Some of you already have "push" access, but I would like to go further. Maintainers would:

1. Have access to the PyPI package.
2. Have complete autonomy in reviewing and merging pull requests.
3. Have complete autonomy in responding to and resolving issues.
4. Be specifically called out in the documentation.

This project is fairly low maintenance but I think with a few more hands it could really shine. Maintainers could put as little or as much time in as they'd like. My only constraint is to follow the Code of Conduct and be kind to each other and our contributors.

Right now my picks for maintainers are:

- @dhermes 
- @lukesneeringer 
- @crwilcox 
- @stsewd 

Please let me know if this is something you'd be interested in doing. If not, that's totally fine. If none of you are up for it right now - that's fine too. I'll try to build up more people from the community to take on this role.

💜

**Comment by theacodes** [comment]
Also, totally forgot to mention: once we have 3 total maintainers (including myself) I will setup an open collective fund to pay maintainers and contributors.

**Comment by lukesneeringer** [comment]
Sure, seems reasonable. I have a couple "planned things" that have not bubbled to the top of my list, but can definitely do normal maintenance work.

**Comment by dhermes** [comment]
> let me know if this is something you'd be interested in doing

I'm in

**Comment by stsewd** [comment]
Thanks! I'm fine with 3 and 4. I don't feel like I'm required for 1, I don't feel really familiar with the codebase for doing 2.

I'm happy just collaborating to the project in general, I like this alternative to tox :)

**Comment by crwilcox** [comment]
I'm also in.

**Comment by theacodes** [comment]
Y'all are amazing. I'm going to get this all set up in the next week. <3

**Comment by theacodes** [comment]
Small update: I'm getting the opencollective setup and then will promote
all of you. :)

**Comment by theacodes** [comment]
Y'all have all been granted contributor access to this repo and maintainer access to the Python package index project.

PR incoming to update the docs and contributing stuff.

**Comment by theacodes** [comment]
Okay done #201. 

Thank you all so much.
