### ISSUE TITLE
Support stdout file redirects in session.run()

### ISSUE THREAD

**Issue by schuderer** [theacodes/nox#218]
**How would this feature be useful?**
When building projects, I find myself having to use commands which generate output to stdout (such as `pipenv lock -r`) which I want to redirect to a file (e.g. `>docs/requirements.txt`). This currently is not possible with `session.run()`, because, as I understand it, special characters such as `>` are being escaped before they are run.

**Describe the solution you'd like**
It would be handy if `session.run()` would accept something like `session.run("echo", "hello", ">hello.txt")` or `session.run("echo", "hello", ">", "hello.txt")` and pass the redirect through so it gets executed when running the command.

**Describe alternatives you've considered**
I am using `Makefile`s and, for cross-platform reasons, `make.bat`. I also played around with task-specific shell/batch files. Having `nox` at hand, I am hoping I can centralize all my test-, but also more general build-related processes into one neat and tidy script, replacing non-Windows-compatible `Makefile`s and reducing clutter.

**Comment by theacodes** [comment]
Hi, we added this in #180. You can do

```python
with open("pipenv-log.txt", "w") as out:
    session.run("pipenv", "lock", "-r", stdout=out)
```

**Comment by henryiii** [comment]
Maybe dumb question: is there a way to get the output directly in a variable, without a file? I don't seem to be get a StringIO/BytesIO to work here, or a `redirect_stdout`. I get `io.UnsupportedOperation: fileno`.

**Comment by henryiii** [comment]
Also, I don't think this was ever documented?

**Comment by henryiii** [comment]
Ahh, output is returned if this is silent. I thought I'd done this somewhere before. (Ironically, probably for something very similar to what I'm doing now, grabbing a version).
