### ISSUE TITLE
Python interpreter not found on conda/win32

### ISSUE THREAD

**Issue by schuderer** [theacodes/nox#219]
**Describe the bug**
Using Anaconda on Windows 10, `nox` skips all sessions that explicitly specify a python version using the session decorator, e.g. `@nox.session(python="3.6")`, even though a python interpreter of the correct version is present in the path:
```
(base) C:\dev\mytest>where python
C:\ProgramData\Anaconda3\python.exe

(base) C:\dev\mytest>python --version
Python 3.6.5 :: Anaconda, Inc.
```

**How to reproduce**

Create a `noxfile.py` with at least one session that explicitly specifies the python version, e.g.
```python
import nox

@nox.session(python="3.6")
def with_version36(session):
    print("With python 3.6")

@nox.session(python="3.7")
def with_version37(session):
    print("With python 3.7")

@nox.session(python="3.7")
def without_version(session):
    print("Without python version")
```

Install Anaconda, open Anaconda Prompt, install nox, navigate to the directory containing the noxfile, and run `nox`:
```
(base) C:\>pip install nox
...
Successfully installed colorlog-3.2.0 nox-2019.5.30

(base) C:\>cd C:\dev\mytest

(base) C:\dev\mytest>nox
nox > Running session with_version36
nox > Session with_version36 skipped: Python interpreter 3.6 not found
nox > Running session with_version37
nox > Session with_version37 skipped: Python interpreter 3.7 not found
nox > Running session without_version
nox > Creating virtualenv using python.exe in .nox\without_version
Without python version
...
```

Checking the location of the interpreter reveals that there is a python 3.6 in the path:
```
(base) C:\dev\mytest>where python
C:\ProgramData\Anaconda3\python.exe

(base) C:\dev\mytest>python --version
Python 3.6.5 :: Anaconda, Inc.
```

I also tried it out in another 3.7-conda environment, even matrioshka'd inside a pipenv environment, with the same results.

**Expected behavior**
I expected both sessions `with_version36` and `without_version` to run.
I think the python interpreter of the correct version should be discoverable on conda, too.

Is `nox` perhaps looking for python binaries by name (expecting python3.exe, python36.exe and so on), instead of finding all interpreters in the path and then checking `--version`?

**Comment by tswast** [comment]
Yes, `nox` looks for binaries by name. I usually end up install all the Python versions from python.org, even if I don't use them for my project development environment, since `nox` usually finds those.

**Comment by schuderer** [comment]
Thanks for the workaround @tswast! What are the chances of a change like this being accepted to `nox` (searching by name first, but also in path, if by-name match not found, check `--version` on binaries without version number)? I would be willing to contribute a PR. :) Would probably need some hints on how to unit test this, though.

Context of my use case: I am in the process of creating a machine-learning-related library where I want to keep the bar low for contributions (hence nox ;) ). I expect contributions particularly from Windows users, where, in the ML realm, Anaconda rules supreme. I was hoping to be able to hide much of the complexity of setting up a dev environment for my library behind `pipenv` and `nox`.

**Comment by theacodes** [comment]
Hrm. Nox tries to find interpreters (by name) in your `PATH` first, failing that on Windows it uses the Python launcher (py.exe) as implemented [here](https://github.com/theacodes/nox/blob/master/nox/virtualenv.py#L61-L85).

If the Conda interpreter is in your path as `python3.6.exe` I'm not sure why it's not finding that.

**Comment by tswast** [comment]
> If the Conda interpreter is in your path as `python3.6.exe` I'm not sure why it's not finding that.

In my experience with conda, they only add a `python` binary, not a versioned name.

**Comment by tswast** [comment]
@schuderer You might want to use the conda `venv_backend` I want to add in https://github.com/theacodes/nox/pull/217

It uses a different way to find Python interpreters, namely by passing the `python=version_num` parameter to `conda create`.

**Comment by theacodes** [comment]
> In my experience with conda, they only add a python binary, not a versioned name.

Oh h*ck.

We *could* add a final case to our resolver that looks for `python.exe` and checks its version if y'all wanted.

**Comment by schuderer** [comment]
> @schuderer You might want to use the `venv_backend="conda"` I want to add in #217
> 
> It uses a different way to find Python interpreters, namely by passing the `python=version_num` parameter to `conda create`.

Thanks, that looks neat! Unfortunately for me, while this is useful for cases where you know beforehand that the contributor running `nox` is using conda, this is (if I understand the PR correctly) not the case if you want to keep it the noxfile as independent as possible.

For this use case, @theacodes' suggestion would fit the bill IMO:
> We could add a final case to our resolver that looks for python.exe and checks its version if y'all wanted.

**Comment by schuderer** [comment]
Update: I tried `py.exe -3.6` and Anaconda3 does not seem to make a py.exe available (command not found). So to me it looks like Thea's suggestion would solve this (for me 😁 ).

**Comment by schuderer** [comment]
I also stared long and hard at Continuum, but they didn't flinch. In other words, not bundling python launcher (py) with Anaconda appears to be a conscious decision, and Continuum won't budge: ContinuumIO/anaconda-issues/issues/149

So, while Anaconda adding py would have been the best solution, it doesn't seem to be very realistic, and nox being able to version-check a python interpreter in the PATH would be the next best solution IMO.
