### ISSUE TITLE
Nox Fails : 'Python Interpreter 3.6 not found', but Python version is present.

### ISSUE THREAD

**Issue by saran001** [theacodes/nox#222]
Hi everyone,

I just now found about nox and started learning about it. I created a simple package and tried automating some tests with nox. I have two Python versions - 2.7.10 and 3.6.5 . I've installed nox in Python 3.6.5 . On trying to run nox for both these versions, I'm getting a warning saying 'Python Interpreter 3.6 is not found'. Here is my nox code :

```
import nox


@nox.session(python=["3.6", "2.7"], reuse_venv=True)
def pytest(session):
    session.install("numpy")
    session.install("pytest")
    session.run("python", "setup.py", "develop")
    session.run("pytest", "-v", "tests")
```  

and this is the result :    

![image](https://user-images.githubusercontent.com/19660860/61682837-d67c0c00-ad30-11e9-9571-ef0c35adc0a5.png)

But I have Python 3.6.5 in my laptop : 

![image](https://user-images.githubusercontent.com/19660860/61682878-f8758e80-ad30-11e9-91f0-f01415aaeb5b.png)

But when I run with only python 3.6, it is working. I'm unable to figure out why this is so. I even tried removing Python 2.7 from the environment PATH variable. Can someone please help me figure out what I'm doing wrong?

**Comment by dhermes** [comment]
This is quite surprising. Can you run `py`, `py -3` and `py -3.6` from the command prompt? Also, when you are within a Python interpreter can you `import sys; print(sys.executable)`?

**Comment by saran001** [comment]
Hi @dhermes, I've run the commands you've mentioned. This is the result I'm getting : 

![image](https://user-images.githubusercontent.com/19660860/61683509-573c0780-ad33-11e9-9e84-b42f89cf9c21.png)

I don't understand. Why am I getting Python 3 and Python 3.6 not found, even though the Interpreter is present?

**Comment by dhermes** [comment]
I'm not sure why the `py` launcher can't find your install. I'd imagine it has to do with how it was installed. Did you personally install it or is your machine administered by someone else (e.g. an IT org)? If you did install it, do you recall how you did it? Could you re-install from a python.org installer?

**Comment by saran001** [comment]
I personally installed it.  I downloaded **python-3.6.5-amd64.exe** from python.org and followed the installation steps mentioned in the installer. I'll try uninstalling both the versions and try re-installing again. Before running `py` launcher, I set `PYLAUNCH_DEBUG=1` and found this :

<img width="948" alt="nox_error1" src="https://user-images.githubusercontent.com/19660860/61684635-b8fe7080-ad37-11e9-85e8-06dc764e81d3.PNG">
<img width="947" alt="nox_error2" src="https://user-images.githubusercontent.com/19660860/61684636-b8fe7080-ad37-11e9-800b-f0176e0bc062.PNG">

**Comment by saran001** [comment]
Solved Issue. It seems there was some problem during the installation of Python 3.6.5 . I uninstalled all python versions and re-installed everything. Now it's working 👍 . Thanks, @dhermes  for your help.

![image](https://user-images.githubusercontent.com/19660860/61692212-d983f600-ad4a-11e9-93bf-c30804a41ce3.png)

**Comment by dhermes** [comment]
Sure thing
