### ISSUE TITLE
shell completion

### ISSUE THREAD

**Issue by cs01** [theacodes/nox#227]
**How would this feature be useful?**

More efficient cli usage. Would autocomplete session names so `nox -l` doesn't have to be typed, and session names don't have to be fully typed out.

**Describe the solution you'd like**

Since nox uses argparse, it can use argcomplete to add tab completion functionality. https://github.com/kislyuk/argcomplete

I just added this to pipx (https://github.com/pipxproject/pipx/pull/182) and I find it is helpful when completing package names. It was very easy to add (argcomplete is awesome!). In nox's case it would be really helpful to auto-complete session names.

**Comment by theacodes** [comment]
I would *love* to see this implemented.

**Comment by cs01** [comment]
I can give it a shot.

**Comment by theacodes** [comment]
I've marked this issue with `open collective eligible` which means that if someone takes this on we can pay them for the work via our [Open Collective](https://opencollective.com/python-nox).
