### ISSUE TITLE
add session argument to tell nox to skip autorunning 

### ISSUE THREAD

**Issue by cs01** [theacodes/nox#232]
**How would this feature be useful?**
Some sessions in the nox file behave kind of like make targets: you want to run them since they automate something, but you don't necessarily want to run them all at once automatically.

For example, usually you want to run unit tests, lint, and document builds when running `nox` to ensure the code is all good. But it's also do things in nox such as `publish`, `blacken`, `watch_docs`, etc, that are run in a one-off basis. 

The nox project itself accomplishes this by opting *in* with the environment variable `NOXSESSION`.

The pipx project has two files: a standard noxfile.py and another file called automation.py.
https://github.com/pipxproject/pipx/blob/master/noxfile.py
https://github.com/pipxproject/pipx/blob/master/automation.py

**Describe the solution you'd like**

Add a new argument to opt *out* of automatically running the session, so that it can *only* be run when specifically called on the cli: `nox -s my_non_automated_session`.

The argument could be something like `autorun=False`, or `run_in_suite` and would default to True if not present.

```
@nox.session(python="3.7", autorun=False)
def blacken(session):
    """Run black code formater."""
    session.install("black")
    session.run("black", "nox", "tests", "noxfile.py", "setup.py")
```

**Comment by theacodes** [comment]
We have this but on a slightly different shelf: you can set `nox.options.sessions` as listed in the second example [here](http://nox.thea.codes/en/stable/config.html#modifying-nox-s-behavior-in-the-noxfile). to accomplish this.

WDYT? Should we add another way to accomplish this or maybe we should better document the existing approach?

**Comment by cs01** [comment]
Oh, nice! This will do!

> WDYT? Should we add another way to accomplish this or maybe we should better document the existing approach?

I would prefer having the autorun keyword argument on the session itself, but I don't really think I have a strong argument for the case. I think in the end this was just me not reading the docs well enough. I am a nox newbie and I kind of assumed it would be in the session object. I am fine closing this issue.

**Comment by theacodes** [comment]
Cool, thank you!
