### ISSUE TITLE
Colorized output is not disabled when output is redirected

### ISSUE THREAD

**Issue by software-dov** [theacodes/nox#266]
**Describe the bug**
Redirecting nox output does not correctly determine that stdout is not a tty and adds color control codes to the output.

**How to reproduce**
Given a noxfile that defines some targets, e.g. unit tests, run
`cd path/to/repo && python -m nox -s &> output-log.txt`

**Expected behavior**
The contents of `output-log.txt` should be plain ASCII (or UTF-8) and not contain cursor control codes.

**Comment by dhermes** [comment]
TIL, neat!

```python
# main.py
import sys


def main():
    print(sys.stdout.isatty())


if __name__ == "__main__":
    main()
```

yields

```
$ python main.py
True
$ python main.py > is_tty.txt && /bin/cat is_tty.txt && rm -f is_tty.txt
False
```

**Comment by dhermes** [comment]
AFAICT we only check if **STDIN** is a TTY and only do it in two places ([1][1] and [2][2]).

[1]: https://github.com/theacodes/nox/blob/aa9290713a4b664ea4ef4da0554afb09a626d7e1/nox/sessions.py#L121
[2]: https://github.com/theacodes/nox/blob/aa9290713a4b664ea4ef4da0554afb09a626d7e1/nox/_options.py#L99

**Comment by software-dov** [comment]
Why does nox care if STDIN is a TTY?

**Comment by theacodes** [comment]
Probably just a mistake on my part. We should change it to stdout.
