### ISSUE TITLE
A Chinese translation for Nox's document

### ISSUE THREAD

**Issue by chinesehuazhou** [theacodes/nox#273]
This is a Chinese document for Nox that I just translated: [here](https://github.com/chinesehuazhou/nox_doc_cn). 

It is my first time translating a document for an open source project and I'm not sure if it is appropriate to submit here, but I hope it can help.

**Comment by theacodes** [comment]
Hi! Is this just the README or did you translate the full documentation over at nox.thea.codes?

**Comment by chinesehuazhou** [comment]
The full documenttation except Changelog

**Comment by theacodes** [comment]
Awesome. I would like to get this up as a proper translation on
readthedocs. https://docs.readthedocs.io/en/stable/localization.html

**Comment by theacodes** [comment]
It seems like this hasn't moved in a while, so I'm going to close it for the time being.
