### ISSUE TITLE
Are more type hints desired?

### ISSUE THREAD

**Issue by Peilonrayz** [theacodes/nox#276]
I was interested in adding a different virtual environment / package manager to nox, independently. And noticed you don't have many type hints. The [`noxfile.py` runs mypy](https://github.com/theacodes/nox/blob/8151acdf0a8206559a0c42e50b0b199c5592da8e/noxfile.py#L70), so I'm thinking the answer is yes.

Are more type hints / static typing desired?

---

If you do:

-   Is there anything you don't want to be typed?
-   If required, are you ok with adding `typing_extensions` as an additional requirement?  
    Should it be avoided at all costs?
-   If a situation arises where mypy errors unless a substantial refactor occurs, what is the desired solution?

    If it's not deemed possible to resolve the situation with type hints or variable annotations alone. Should the error be silenced, `# type: ignore`, and a todo, `# TODO: ...`, be added?

**Comment by cs01** [comment]
I am not a maintainer but I added the mypy  checks and type hints in https://github.com/theacodes/nox/pull/230, and expanded coverage in a few subsequent PRs. 

Yes, they would like more type coverage. I don’t think there is anything that shouldn’t be typed. I know there is push for not adding new end-user dependencies to this project, so if you need that package, it would be preferable to only install it in the nox lint session where mypy is run. 

I have also run into cases where a substantial refactor is needed. In my experience, the maintainers prefer you make a PR with just the minimal refactor (to keep the diff reviewable), then add types in another PR. 

I have been adding “type: ignore” where tricky things have arisen. I think that’s fine going forward. If we ever want to go back and fix them we can do a search for “type: ignore”. Right now nothing is typed so typing 99% of the code with a few ignores is much better than keeping none of it typed.

**Comment by Peilonrayz** [comment]
Ok, that all sounds reasonable. Adding `typing_extensions` to just the lint session should be possible, if not a handy `# type:ignore` should suffice.

I'll start work on this soon, but I don't think I'll have any PRs for at least a week.

**Comment by theacodes** [comment]
I couldn't have said it any better than @cs01. I'd love more type hints. :)

**Comment by Peilonrayz** [comment]
With the merger of #282 100% of the code has been typed. I'm going to close this as further issues should probably be their own issues.
