### ISSUE TITLE
Log timestamp in logging formatter

### ISSUE THREAD

**Issue by omry** [theacodes/nox#289]
**How would this feature be useful?**
I am looking at some long CI sessions and there is no way for me to know what is slowing the session down.
Adding a log timestamp prefix (optionally) can make it easier to determine that by looking at the time difference between subsequent log lines.

**Describe the solution you'd like**
```python
import nox

nox.logger.pattern = "[%(asctime)s][%(cyan)s%(name)s > %(log_color)s%(message)s"

# everything normal from here.
```

**Describe alternatives you've considered**
Maybe a configuration file is in order.

**Comment by theacodes** [comment]
Yup, I'm totally for this. I'd also be fine if we did this if `--verbose` is passed.

**Comment by stsewd** [comment]
This was solved in https://github.com/theacodes/nox/pull/323
