### ISSUE TITLE
Universal wheel when Python 2.7 support has long been dropped

### ISSUE THREAD

**Issue by schuderer** [theacodes/nox#291]
More of a cleanup suggestion really. 

**Describe the bug**
Nox ist still distributed using a universal wheel, while at the same time, Python 2.7 is not supported.

I am not 100% sure about the repercussions of this (tools checking compatibility and maybe claiming nox would work when it wouldn't?), but it seems sensible to remove the `universal` config setting.

In any case, it would make it possible to outright remove `setup.cfg`, making the project directory just a *tad* cleaner. :)

**How to reproduce**
Nox's [wheel file on PyPI](https://pypi.org/project/nox/#files) has contains the identifier `py2.py3`.
`setup.cfg` contains:
```ini
[bdist_wheel]
universal = 1
```

**Expected behavior**
No inadvertent hinting of Python 2 compatibility. One fewer config file. 🎉

**Comment by theacodes** [comment]
oh yeah, let's nix that. Wanna send a PR?

**Comment by schuderer** [comment]
PR has been approved and merged by @dhermes.
