### ISSUE TITLE
How to create environments with pyenv?

### ISSUE THREAD

**Issue by rsalmei** [theacodes/nox#296]
Hello,

I can't run the following noxfile, could you help me?
```
import nox


@nox.session(python=['2.7', '3.6', '3.7', '3.8'])
def tests(session):
    session.run('make', 'install')
    session.run('pytest')
```

It can't find one or more python interpreters:
```
nox > Ran multiple sessions:
nox > * tests-2.7: success
nox > * tests-3.6: failed
nox > * tests-3.7: success
nox > * tests-3.8: failed
```

But I do have them installed, I use `pyenv` to manage my python interpreters:
```
$ pyenv versions --skip-aliases
  system
  2.7.15
  2.7.15/envs/clearly27
  3.6.6
  3.6.6/envs/clearly36
  3.6.6/envs/tsp
  3.6.6/envs/wsaver
  3.7.3
  3.7.3/envs/about-time
  3.7.3/envs/alive-progress
  3.7.3/envs/clearly37
  3.8.0
```

In this dir I'm using a virtualenv of the `3.7.3` one:
```
$ pyenv version
about-time (set by /Users/rogerio/Documents/projects/about-time/.python-version)```
```

In fact, I really can't call them:
```
$ python3.6
pyenv: python3.6: command not found

The `python3.6' command exists in these Python versions:
  3.6.6
```

If I change to 3.8.0 for example, 2.7, 3.7 and 3.8 works, only 3.6 doesn't:
```
nox > Running session tests-3.6
nox > Creating virtual environment (virtualenv) using python3.6 in .nox/tests-3-6
nox > Command /Users/rogerio/.pyenv/versions/3.8.0/bin/python3.8 -m virtualenv /Users/rogerio/Documents/projects/about-time/.nox/tests-3-6 -p python3.6 failed with exit code 1:
RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.6'
nox > Session tests-3.6 failed.
```

Any clues, please?
I'd like to include nox in all my projects, testing first in `about_time`...
Thank you!

**Comment by pscosta5** [comment]
This is more of a pyenv usage question.

One way to make pyenv aware that you want multiple versions of Python is to specify it in your `.python-version` file. An easy way to do this for a project is to use the `pyenv local` command. Let's pretend you have a project that supports 3.7 and 3.8.

```sh
❯ pyenv versions
3.7.6
3.8.1

❯ pyenv local 3.8.1 3.7.6
3.8.1
3.7.6

❯ python3.8 -V
Python 3.8.1

❯ python3.7 -V
Python 3.7.6
```

**Comment by rsalmei** [comment]
Wow, thank you! Have never heard about this notation, despite using pyenv for several years!
Even the `--help` doesn't say anything about the ability to send more than one:
```
<version> should be a string matching a Python version known to pyenv.
The special version string `system' will use your default system Python.
```

Well, that line did the trick:
```
pyenv local about-time 2.7.17 3.5.9 3.6.10 3.8.2
```

Very nice tool this `nox`, I'm going to include in my projects!
Check them out: [alive-progress](https://github.com/rsalmei/alive-progress), [clearly](https://github.com/rsalmei/clearly) and [about-time](https://github.com/rsalmei/about-time).

Thanks again!
