### ISSUE TITLE
Add a command line option for setting python=False

### ISSUE THREAD

**Issue by sethmlarson** [theacodes/nox#301]
**How would this feature be useful?**
If you have a `noxfile.py` that you use for development but also use `Docker` as a part of your CI you can skip having to create a virtualenv and reinstall dependencies that may have been installed as a part of your Docker image build step. For instance if I have:

```dockerfile
FROM python:3

COPY dev-requirements.txt .
RUN python -m pip install -r dev-requirements.txt

COPY . .
RUN nox -s test --use-current-env
```

then my `session.install("-r", "dev-requirements.txt")` step within my `noxfile.py` would only require checking cache, much faster to run. 

**Describe the solution you'd like**

Using `--use-current-env` (or alternative name, I'm fine with anything!) would override any `python=[]` within `noxfile.py` to `python=False` and use interpreter at `sys.executable`.

**Comment by theacodes** [comment]
I *thought* we already had this, but I'm not opposed to a venv backend that's a"passthrough".

**Comment by smarie** [comment]
There seem to be something like this already : from the [doc](https://nox.thea.codes/en/stable/config.html#configuring-a-session-s-virtualenv)

> If you want to disable virtualenv creation altogether, you can set `python` to `False`

However you cannot use `install` nor `conda_install` then, you get `ValueError: A session without a virtualenv can not install dependencies.` or `ValueError: A session without a conda environment can not install dependencies from conda.`.

I'll try to propose something to fix this

**Comment by smarie** [comment]
PR #316 provides a solution to this: you can now use `--force-venv-backend` (or `-fb`) to force a venv backend for all sessions to be run. Among supported backend, I added the `"none"` backend that is strictly equivalent to `python=False`. See #316 for details, there is also a new option to define the default venv backend.
