### ISSUE TITLE
Move --keywords argument to the primary group

### ISSUE THREAD

**Issue by maciej-lech** [theacodes/nox#303]
Hello.

I see that `--keywords` argument does not belong to any of `nox` `argparse` group that why `argparse` is placing it in _optional arguments_ by default. As nox is using argparse groups for any other arguments, we should consider moving `--keywords` to _primary group_ and force using group in `Option` class, ihmo.

**Describe the bug**
```
optional arguments:
  -k KEYWORDS, --keywords KEYWORDS
                        Only run sessions that match the given expression.
```

**How to reproduce**
`$ nox -h` :smiley:

**Expected behavior**
```
Primary arguments:
  These are the most common arguments used when invoking Nox.

  -h, --help            Show this help message and exit.
  --version             Show the Nox version and exit.
  -l, --list-sessions, --list
                        List all available sessions and exit.
  -s [SESSIONS [SESSIONS ...]], -e [SESSIONS [SESSIONS ...]], --sessions [SESSIONS [SESSIONS ...]], --session [SESSIONS [SESSIONS ...]]
                        Which sessions to run. By default, all sessions will run.
  -k KEYWORDS, --keywords KEYWORDS
                        Only run sessions that match the given expression.
  posargs               Arguments following ``--`` that are passed through to the session(s).
```

**More improvements in help message**
One more thing to consider that can improve the readability of the help message is to instead of having _primary/additinal_ groups we could split the arguments into more functional-oriented groups e.g.:
- general: --help, --version, --verbose, --noxfile, posargs
- reporting: --nocolor, --forcecolor, --report
- collection: --list, --session, --keywords
- environment: --envdir, --reuse-existing-virtualenvs, etc.
- execution: --stop-on-first-error, --install-only, --non-interactive, etc.

I based above on `pytest --help`

Best regards,
Maciej

**Comment by theacodes** [comment]
I would be happy to see a PR moving things in to functional-oriented groups.

**Comment by maciej-lech** [comment]
Great :) I'll create a separate ticket for having functional-oriented groups and in this one, we can simply prevent using `group=None`.

**Comment by maciej-lech** [comment]
Here is a new ticket #305

**Comment by stsewd** [comment]
This was done in https://github.com/theacodes/nox/pull/306
