### ISSUE TITLE
Functional-oriented `argparse` groups

### ISSUE THREAD

**Issue by maciej-lech** [theacodes/nox#305]
The idea is to have functional-oriented `argparse` groups.

**How would this feature be useful?**
It will increase the readability of the help message.

**Describe the solution you'd like**
Instead of having primary/additinal `argparse` groups we can split the arguments into more functional-oriented groups e.g.:
- general: --help, --version, --verbose, --noxfile, posargs
- reporting: --nocolor, --forcecolor, --report
- collection: --list, --session, --keywords
- environment: --envdir, --reuse-existing-virtualenvs, etc.
- execution: --stop-on-first-error, --install-only, --non-interactive, etc.

I based above on `pytest --help`

**Comment by theacodes** [comment]
I'm all for this and it would be a good first issue for someone to tackle

**Comment by DrGFreeman** [comment]
Hello, I'd like to work on this issue if it's OK. Thx.
