### ISSUE TITLE
Debugging tools and user guide

### ISSUE THREAD

**Issue by smarie** [theacodes/nox#308]
(edited)

I'm new to `nox`, trying it as I definitely like the python-first philosophy, and `conda` seems supported out of the box so .. yay :)

My first reaction when trying it was to try to import the dependencies from my `pyproject.toml` and `setup.cfg` "tests_requires" variables, so that I do not have to move them around *again*.

Since I did not find this in the doc, I decided to try to code it myself in the `noxfile.py`, after all it should be relatively straightforward.

 - I managed to run nox in debug mode by creating a pycharm configuration running `<my_env>\Lib\site-packages\nox\__main__.py` in my project's folder. Maybe inexperimented users will not be able to reach that point so maybe **adding a "debugging" section in the doc could be good** ?

 - I started to code in my nox session functions, but when wanting to print debug messages I found out that my messages were not showing in the right order with nox logs in the terminal. This is because I used `print` and nox uses `logging.warning`. Maybe nox could provide a few high level functions such as `nox.info()`, `nox.warning()`... whatever seems relevant - so that users do not have to spend time setting up loggers, colors, etc. For example `click` provides an [`echo` function](https://click.palletsprojects.com/en/7.x/quickstart/#echoing). The simplest workaround is to tell users to do `nox_logger = logging.getLogger("nox")` in their `noxfile.py` and then use the usual api. But that might not be the most elegant API. EDIT: I found [this .log method](https://nox.thea.codes/en/stable/config.html#nox.sessions.Session.log) - is it enough? If so we should refer to it from the abovementioned "debugging" doc section (if created)

 - (EDIT) I am currently trying to solve an issue with conda not behaving correctly with the `pip` command because the environment is not activated. Debugging such an issue could be eased by having a documentation section explaining how to make the conda/pip/other commands outputs appear in the logs. As of now it seems that I have to set the level to DEBUG - 1 ("OUTPUT").

I'm sure you may have other ideas on that topic of helping users taking control of their noxfile customizations and feeling confident editing it - do not hesitate to discuss them here as well

Thanks again for this great tool!

**Comment by smarie** [comment]
Concerning the first of the above bullet points, there could be some easy way to provide quick debugging capabilities in PyCharm and other IDEs: simply provide a `nox.run()` method accepting to receive the `noxfile.py` globals. This would make the `noxfile.py` module directly runnable from any IDE by including the following at the end:

```python
#! /usr/bin/env python3

@nox.session(python=["3.8"])
def dummy(session):
    pass

if __name__ == '__main__':
    # allow this file to be executable
    nox.run(globals())
```

Note: this idea is not actually from me but from doit: https://pydoit.org/cmd_run.html#using-the-api , I find it quite cool.

In parallel for information I asked PyCharm to better support nox : https://youtrack.jetbrains.com/issue/PY-37302 (and yes, I forgot that I did it so I reopened a second duplicate ticket more recently :) ). But this can not replace good explanation on how to debug IMHO.

**Comment by theacodes** [comment]
I think for now supporting direct debugging of Nox's internals isn't something we want to document for end users, but if someone is willing to pick this up and write the docs, I'll be happy to review.
