### ISSUE TITLE
ModuleNotFoundError: No module named 'nox' after pip installation

### ISSUE THREAD

**Issue by staticdev** [theacodes/nox#321]
**Describe the bug**
I have upgraded Ubuntu to 20.04, it seems nox got uninstalled. I have `pip install --user nox`, also `pip install nox` and got successful installation on both.

**How to reproduce**
I run `nox` on a project with nox config files and get the error:
```
Traceback (most recent call last):
  File "/home/user/.local/bin/nox", line 6, in <module>
    from nox.__main__ import main
ModuleNotFoundError: No module named 'nox'
```

**Expected behavior**
nox run as usual.

**Comment by theacodes** [comment]
Do you have a file named "nox.py" or a folder named "nox" in your current
directory?

**Comment by staticdev** [comment]
@theacodes nope.. I have a .nox folder and a noxfile.py.

**Comment by staticdev** [comment]
There is a problem with Ubuntu upgrade. I just uninstalled and installed again and it worked.
