### ISSUE TITLE
Alternate cmd style for `session.run` and additional `session.run_cmds` to run several commands from a multiline string or text file

### ISSUE THREAD

**Issue by smarie** [theacodes/nox#329]
**How would this feature be useful?**

One feature from tox that I am missing in nox is the ability to "see" my command as a simple text line, and also to pass several commands in a row. The most pythonic equivalent seems to be a multiline string containing the commands:

```python
cmds = """
dir
echo "hello_world"
"""
```

Even without going for multiline, I find it a bit unelegant having to write this:

`session.run(*'echo "hello_world"'.split(' '))`

instead of this:

`session.run('echo "hello_world"')`

**Describe the solution you'd like**

 - For one-line commands, maybe we could modify `session.run` so that it accepts a single string containing space-separated command and arguments ?

 - For multiline commands (several commands, one per line), a new `session.run_cmds()` method able to run commands either from a multiline string or a multiline text file.

```python
session.run_cmds(cmds_str=None, cmdsfile_path=None, 
                       env: Mapping[str, str] = None,
                       silent: bool = False, success_codes: Sequence[int] = (0, ), external: bool = False
)
```

Behind the scenes, after splitting lines, stripping them and keeping only the non-empty, it would call `session.run(*line.split(' ')), **kwargs`

(note: it should not split the spaces sitting between double quotes)

**Comment by smarie** [comment]
Afterthought: actually we could support all of these features in the same `run` method, without ambiguity. The rare case where the newline symbol would be in the command could be resolved by splitting it manually. I'll push a PR.

**Comment by theacodes** [comment]
Nox requiring commands to be specified as a list of strings is intentional to help avoid common errors with specifying arguments to subprocesses.

I'm inclined not to add this, but I'm curious what the other maintainers think.

**Comment by smarie** [comment]
Which common errors do you have in mind ?

At least for my usage of nox, all cases that I encountered so far were cases where stripping/splitting the command according to spaces (with the subtelty of not splitting a space that is inside double quotes) would provide the exact same result than having me split the command into a tuple of strings.

With one major difference though: readability. Indeed, it is much easier to read my own code when the commands are full strings rather than tuples of strings. This is especially true when I execute several commands in a nox session.

ok let's wait for other maintainers' feedback!

**Comment by theacodes** [comment]
I think for now I'm -1 on including this, and no other maintainers have chimed in. Happy to change my mind if other folks have thoughts, but for now I'm going to close this.
