### ISSUE TITLE
PEP 561 marker file py.typed missing from releases

### ISSUE THREAD

**Issue by lschmelzeisen** [theacodes/nox#336]
While there is a [PEP 561](https://www.python.org/dev/peps/pep-0561/) maker file in `nox/py.typed` it is not included in the published releases. To reproduce, extract the published [nox-2020.5.24.tar.gz](https://files.pythonhosted.org/packages/6b/a6/e3f1bdadf1d1eeed17a5cb431796711ae06f8a78107f5f60040fa0d5ac07/nox-2020.5.24.tar.gz) and see that the file is missing.

Mypy therefore does not know that this package includes type annotations and will display errors to users.

I'm actually not sure why the marker file is not included in the releases. The `setup.py` specifically includes it in the package data:

https://github.com/theacodes/nox/blob/00775b470129787b14c45f2853441f9f1cad006d/setup.py#L49

However, this setting might be ignored and perhaps adding the following line to the `MANIFEST.in` is the correct solution:

```
included src/py.typed
```

I would appreciate it, if the correct setting can be found and this published as a bugfix release.

**Comment by lschmelzeisen** [comment]
Any statement/action on this? IMO this should be a relatively quick fix.

**Comment by theacodes** [comment]
I'd be happy to review a PR for this. :)
