### ISSUE TITLE
Export Session in __init__

### ISSUE THREAD

**Issue by layday** [theacodes/nox#343]
**How would this feature be useful?**
Currently, if you'd like to annotate nox callbacks, for e.g. type checking, code completion or docstring lookup, you have to import `Session` from `nox.sessions`:

```py
import nox
from nox.sessions import Session


@nox.session
def foo(session: Session):
    ...
```

Re-exporting `Session` in `__init__` would 'jibe' with nox's global object approach and would perhaps make typing in nox more accessible.

**Describe the solution you'd like**
For the `Session` class to be imported/re-exported in `nox.__init__` so as to not require a separate import.

**Describe alternatives you've considered**
Importing `Session` from `nox.sessions`, as above.

**Comment by theacodes** [comment]
Go for it!
