### ISSUE TITLE
Some conda commands not logged.

### ISSUE THREAD

**Issue by mforbes** [theacodes/nox#345]
When using `venv_backend="conda"`, the `conda create` command is not logged, even if `-v` is provided, since `log=False` is hard-coded in [`nox/virtualenv.py`](https://github.com/theacodes/nox/blob/master/nox/virtualenv.py#L243):

```python
        nox.command.run(cmd, silent=True, log=False)
```

From the docs, I expected that running `nox -v` would log all commands.

**Comment by henryiii** [comment]
I started to try to help with this, but ran into an incorrect type, which prompted #455. After that is fixed, then I can try to help with this.

**Comment by FollowTheProcess** [comment]
Hi @henryiii! 

Are you still working on this?

If you're busy I wouldn't mind taking a crack at this 😃 but don't want to just take it without checking first!

**Comment by henryiii** [comment]
I haven't gotten back to this yet (and am unlikely to before SciPy is over). Also, I'll probably work on #448 next since I already have a PR open for that - so feel free to work on this, I'll avoid starting on it for now!
