### ISSUE TITLE
Allow session.install to be able to use installers other than 'pip' 

### ISSUE THREAD

**Issue by mkokshoorn** [theacodes/nox#349]
**How would this feature be useful?**

It would be very useful to be able to use other pip-like packages like 'pip_accel' (a layer on top of pip that handles package caching much faster (see [pip_accel](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiwheG2nfLrAhXSs54KHVfrDAQQFjAAegQIBhAB&url=https%3A%2F%2Fpypi.org%2Fproject%2Fpip-accel%2F&usg=AOvVaw11LTvV5DylBo04zijD1IWC))

**Describe the solution you'd like**

I think the simplest solution might just be for `session.install()` to support a default argument like `base_command="pip install"`. 

With this, it would be backward compatible, and users can do things like `session.install( "pandas", base_command="pip_accel install")`

I'm sure there's a better name than `base_command` but hopefully, this gives the idea of one possible solution.  

**Describe alternatives you've considered**

I realize it is possible to just use the session.run() API (e.g., session.run("python", "-m",  "pip_accel", "install"...), but then this means that when I use nox's '--install-only' feature, it gets skipped and I need this in my workflow.

**Comment by danieleades** [comment]
Related- #347

**Comment by theacodes** [comment]
I think for now I'd prefer that you use `session.run_always` for commands for other installers. Happy to continue discussing if that doesn't work for you.

Closing for now, though.

**Comment by mkokshoorn** [comment]
That will work will! I hadn't seen that one, thanks!
