### ISSUE TITLE
windows + conda : nox using an interpreter that does not exist

### ISSUE THREAD

**Issue by omry** [theacodes/nox#352]
This is probably related to some change in my CI, but I am having a hard time figuring it out.

**Describe the bug**
nox is trying to use a Python interpreter that is not there:
```
(hydra) PS C:\Users\circleci\project> where.exe python
where.exe python
C:\tools\miniconda3\envs\hydra\python.exe
(hydra) PS C:\Users\circleci\project> nox -s lint-3.8
nox -s lint-3.8
nox > Running session lint-3.8
nox > Creating virtual environment (virtualenv) using python.EXE in .nox\lint-3-8
Operating system        :       Windows
NOX_PYTHON_VERSIONS     :       ['3.6', '3.7', '3.8']
PLUGINS                 :       ['ALL']
SKIP_CORE_TESTS         :       False
FIX                     :       False
VERBOSE                 :       0
INSTALL_EDITABLE_MODE   :       0
nox > Command c:\tools\miniconda3\envs\hydra\python.exe -m virtualenv C:\Users\circleci\project\.nox\lint-3-8 -p C:\tools\miniconda3\envs\hydra\python.EXE failed with exit code 1:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\tools\\miniconda3\\envs\\hydra\\Lib\\venv\\scripts\\nt\\python.exe'
nox > Session lint-3.8 failed.
(hydra) PS C:\Users\circleci\project> 

```

**How to reproduce**
This is only happening in CircleCI, so I am not sure what is actually causing it (I tested on Windows 10 with conda and it works there).
It was also working fine until it broke without any apparent change.

Any hints on how to debug or workaround?

**Comment by drewgilliam** [comment]
FYI - conda and virtualenv 20.0.34 aren't playing well together.  see https://github.com/pypa/virtualenv/issues/1986 and https://github.com/ContinuumIO/anaconda-issues/issues/12094

**Comment by omry** [comment]
This explains it, thanks @drewgilliam.
One of the comments suggest `virtualenv==20.0.33` as a workaround, I will give it a shot as a temporary solution.

**Comment by theacodes** [comment]
For now we'll just wait for virtualenv to fix this unless y'all think we can do anything here to mitigate.
