### ISSUE TITLE
Migrate from travis-ci

### ISSUE THREAD

**Issue by stsewd** [theacodes/nox#368]
Now that travis cut the number of builds for open source projects, builds are very slow. I think moving to github actions should be good?

**Comment by theacodes** [comment]
Sounds good. I don't have the time to do this right now, but if anyone else
wants to jump on it that'd be awesome 😊

**Comment by ichard26** [comment]
Hey, just a little ping that this should be closed as it's been completed by GH-389. My apologies if I'm mistaken.

**Comment by stsewd** [comment]
Yeah, this can be closed. Thanks!
