### ISSUE TITLE
Make site packages directory available in session

### ISSUE THREAD

**Issue by drhagen** [theacodes/nox#387]
**How would this feature be useful?**
Tox has a magic variable called [`envsitepackagesdir`](https://tox.readthedocs.io/en/latest/config.html#substitutions-for-virtualenv-related-sections) that evaluates to the `site-packages` directory of the environment. This is particularly useful for telling coverage where my package is, when I have installed my package into the environment.

**Describe the solution you'd like**
The right place to put this would seem to be at `Session.virtualenv.site_packages`. I think that, just like `location`, this would probably not be defined for `venv_backend='None'`. I would like to invite some discussion on the best way to actually compute this. One way is to manually construct this:

```python
if platform.system() == "Windows":
    site_packages = f'{session.virtualenv.location}/Lib/site-packages'
else:
    site_packages = f'{session.virtualenv.location}/lib/python{session.python}/site-packages'
```

A better way would be query the environment's Python's `site.getpackages()`, which returns a list of all site-package directories, but I am not familiar enough with nox to know how to do that. You may even want to expose `site_packages_paths` the same way as `bin_paths` is done today. I would defer the actual design to the maintainers.

**Describe alternatives you've considered**
I thought that `site.getpackages()` might work with a decorated session function, but that only returns the site-packages directory of the invoking interpreter.

The [current workaround](https://stackoverflow.com/a/66191790/1485877) is to compute the site-packages directory using `location` and `package.system`:

```python
import nox

@nox.session()
def test(session):
    if platform.system() == "Windows":
        site_packages = f'{session.virtualenv.location}/Lib/site-packages'
    else:
        site_packages = f'{session.virtualenv.location}/lib/python{session.python}/site-packages'

    session.install('.')
    session.install('pytest', 'pytest-cov')
    session.run('pytest', '--cov', f'{site_packages}/mypackage')
```

Note that I am interested in making the PR for this feature.

**Comment by theacodes** [comment]
I like it. What does tox do to determine the location?

It's totally valid for us to use `nox.popen` to invoke the session's interpreter to grab the site-packages directory, we should just be sure to cache it.

**Comment by theacodes** [comment]
Some prior art of us using `py.path.sysexec` to interrogate the python interpreter: https://github.com/theacodes/nox/blob/db6378377a58dd678518b1fc1c50fb3c49dbb98a/nox/virtualenv.py#L137

**Comment by drhagen** [comment]
> What does tox do to determine the location?

tox does it like you recommended with [popen](https://github.com/tox-dev/tox/blob/4b445849469699717cca324fa4d61f31141ec287/src/tox/interpreters/__init__.py#L49).

What is your preferred style for cached properties? I could use [cached-property](https://pypi.org/project/cached-property/) or do it manually.

**Comment by theacodes** [comment]
We prefer not to add new dependencies, so just do it manually.

**Comment by drhagen** [comment]
The more I look into this, the more I think that tox's `envsitepackagesdir` is usually an anti-pattern, at least for my purpose of determining where my package is. This is actually not valid in the case where I don't install my package, but my package is still importable because I don't have a `src` directory. I think the correct way to do this is to run this script in the environment:

```python
from importlib.util import find_spec

spec = find_spec('mypackage')
if spec.submodule_search_locations is not None:
    # Is a package
    print(spec.submodule_search_locations[0])
else:
    # Is not a package
    print(spec.origin)
```

I think this is correct for everything except people who do `__path__` manipulation, but no one does that :-).

A function like `session.find_module('mypackage')` (or `module_path`) would be nice. Basically everyone who does coverage needs this, but I'd understand if you thought that was too specialized for `nox`. (This has also made me realize that this is probably more of a problem with `coverage`, which should take the module, instead of the path to discover sources.)

**Comment by cjolowicz** [comment]
@drhagen Just curious, I usually have something like the following in my coverage configuration:

```toml
[tool.coverage.paths]
source = ["src", "*/site-packages"]
```

(I guess you'd replace `src` by the name of your package.)

This configuration does not depend on the exact location of the virtual environment. Wouldn't that solve your use case, or am I missing something here?

**Comment by drhagen** [comment]
> Wouldn't that solve your use case, or am I missing something here?

[`tool.coverage.paths`](https://coverage.readthedocs.io/en/coverage-5.4/config.html#paths) merely controls which paths are considered equivalent for the purpose of reporting. It does not control which files actually get coverage measured. For that, you have to pass `--source` or, in the case of `pytest-cov`, `--cov`.

**Comment by cjolowicz** [comment]
Oh I see. But `--source` does accept package names. So couldn't you just specify your package name in [tool.coverage.run.source](https://coverage.readthedocs.io/en/coverage-5.3/source.html#execution)?

**Comment by drhagen** [comment]
> But --source does accept package names.

Oh my goodness, it does work. I've been doing this wrong for years. Well, this feature is clearly not needed.
