### ISSUE TITLE
parametrize doesn't work as expected with multiple Python versions

### ISSUE THREAD

**Issue by smithfred** [theacodes/nox#395]
Given the following:

```python
@nox.session(python=["3.8", "3.9"])
def test(...
```

I can run `nox -s test` and Nox will run `test-3.8` and `test-3.9`.

However, given the following:

```python
@nox.session(python=["3.8", "3.9"])
@nox.parametrize("foo", ["bar", "baz"])
def test(...
```

I cannot then run `nox -s "test(foo='bar')"` and have Nox run `test-3.8(foo='bar')` and `test-3.9(foo='bar')`.

**Comment by theacodes** [comment]
This is expected behavior. You can explicit ask nox to just run with one of
the interpreters.

**Comment by smithfred** [comment]
I don't understand.

What I mean is, I would expect that if I run `nox -s "test(foo='bar')"`, then it would run both `test-3.8(foo='bar')` and `test-3.9(foo='bar')`, but this doesn't work.

**Comment by smarie** [comment]
As a workaround @smithfred , the following should work:

```python
@nox.session
@nox.parametrize("python", ["3.8", "3.9"])
@nox.parametrize("foo", ["bar", "baz"])
```
