### ISSUE TITLE
Add a default session list

### ISSUE THREAD

**Issue by duggelz** [theacodes/nox#40]
Invoking `nox` with no command line arguments runs every session.  It would be useful if the nox.py could specify a default list of sessions to run in that case, for example

```
nox.default_sessions([ 'lint', 'tests' ])
```

**Comment by duggelz** [comment]
CC @lukesneeringer

**Comment by lukesneeringer** [comment]
My suggestion is to actually make whether or not a session is a "default" session be part of session registration, e.g.

```python
@nox.session(run_by_default=False)
def peekaboo():
    ...
```

This has a few limitations:

  * It only works if you use the `@nox.session` decorator; if you rely on `session_foo` function names, no dice. I assert this is fine.
  * There is no particularly good way to take a subset of parametrized sessions. So, in other words, while `nox.default_sessions(["unit_tests(python_version='3.6')"])` would be easy (but eww!), it would be downright impossble if `run_by_default` only took a boolean. I assert this is also fine, and excluding parametrization should be done with `session.skip`
      * If we really needed this in the future, we could also make `run_by_default` accept a tuple with the permutations to run by default.

**Comment by jonparrott** [comment]
I could go either way on this, but just noting that pytest's parametrize has `pytest.param` specifically for adding more information (marks) to individual runs:

```python
# content of test_expectation.py
import pytest
@pytest.mark.parametrize("test_input,expected", [
    ("3+5", 8),
    ("2+4", 6),
    pytest.param("6*9", 42,
                 marks=pytest.mark.xfail),
])
def test_eval(test_input, expected):
    assert eval(test_input) == expected
```

If we want to go down the route that @lukesneeringer is suggesting we could do:

```python
@nox.session
@nox.parametrize('foo, bar', [
     (1, 2),
     nox.param(3, 4, run_by_default=False)
])
```

**Comment by lukesneeringer** [comment]
If we did that, would the entire kaboodle be an initial requirement, or just the more general case?

**Comment by jonparrott** [comment]
I'd strongly prefer a full solution over a partial one.

It's also perhaps useful to just adopt pytest's marks. We could just have
@nox.mark.default - if any thing is marked as default then running `nox`
alone will only run those sessions, if nothing is marked as default then
all sessions are run.

**Comment by lukesneeringer** [comment]
I could get behind `@nox.mark.default` so long as if _nothing_ is marked default, they all are.

Should we change to `@nox.mark.parametrize`?

**Comment by jonparrott** [comment]
Eh, I'd be okay with just `nox.default` and `nox.parametrize`. I don't think our API surface will be big enough to need to separate those into a `mark` namespace.

**Comment by pradyunsg** [comment]
Agreed. I don't think nox needs a complete mark namespace.

**Comment by stsewd** [comment]
I would love to have an env variable for this, tox has `TOXENV`, when it is defined and you run `tox`, only that environment is ran. For nox we could have `NOXSESSION`.

**Comment by theacodes** [comment]
@stsewd that would be much easier to do than this proposal, and could be done independently.

**Comment by SethMichaelLarson** [comment]
I'm going to take a stab at implementing this, just signaling to anyone else if it's already in progress.

**Comment by theacodes** [comment]
Closing this in favor of #141, let's move the discussion there.
