### ISSUE TITLE
Support `python -m nox`

### ISSUE THREAD

**Issue by dhermes** [theacodes/nox#43]
Currently this fails because `nox` is a package and `nox.py` doesn't exist.

**Comment by jonparrott** [comment]
Seems we shot ourselves in the foot here, because the configuration file is named `nox.py` and therefore `python -m nox` will load that file instead of the "real" nox package/module.

We could add a secondary module just for this, e.g., `python -m noxrunner`. WDYT?

/cc @lukesneeringer

**Comment by theacodes** [comment]
Closed by 431755c3f512de7624b7740ffa3d26318c19de20
