### ISSUE TITLE
Lint session fails following tests-3.x session runs

### ISSUE THREAD

**Issue by DrGFreeman** [theacodes/nox#443]
**Describe the bug**
In the nox repository, when running the `lint` session after having run one of the `tests-3.x` sessions, flake8 fails on analysis of the test generated virtual environments in `tests/resources/.nox/`:

```
nox > flake8 nox tests noxfile.py setup.py
... (lines skipped)
tests/resources/.nox/test-arg-datetime-datetime-1980-1-1-0-0/lib/python3.9/site-packages/wheel/bdist_wheel.py:140:72: W504 line break after binary operator
nox > Command flake8 nox tests noxfile.py setup.py failed with exit code 1
nox > Session lint failed.

```

**How to reproduce**

Run `nox -s tests-3.8 lint`

**Expected behavior**

The `lint` session passes without errors.

**Notes**

- This can be fixed by adding `exclude = .nox` in the `.flake8` file.
- This is not detected in CI since the `lint` job runs in isolation from the test jobs.

**Comment by cjolowicz** [comment]
Thank you for catching and reporting this @DrGFreeman :)

#445 avoids creating a `.nox` directory under `tests` in the first place. That should fix this issue.
