### ISSUE TITLE
conda: support for Mamba

### ISSUE THREAD

**Issue by henryiii** [theacodes/nox#444]
**How would this feature be useful?**

It would be great to support `mamba`, which is a conda replacement solver that is dramatically faster. A solve of a complex package like ROOT (which is a reason to use conda in the first place) takes several minutes with conda, and a few seconds with mamba.

**Describe the solution you'd like**

Option 1: Provide a new backend: `"mamba"`. This would simply make `conda_install(...)` use mamba instead of conda. This is the best option I could think of.

Option 2: Automatically use mamba if available over conda. This is slightly too magical, and there are _minute_ difference in the solve (that shouldn't matter).

Option 3: Add a setting to select the command used for conda. I don't think there is a good reason to generalize too much - mamba is a drop-in replacement for part of conda (other parts can just use conda, as it's always available with mamba).

This was mentioned in https://github.com/theacodes/nox/issues/346#issue-695644289 as a side note, but never attempted.

**Comment by theacodes** [comment]
I'm all for having a `mamba` backend in addition to the conda one. I don't think we should automatically switch to mamba if it's available, since it doesn't completely support all of `conda`'s options and can differ behaviorally - I wouldn't want to break the principle of least surprise.

FYI for my future self or others unfamiliar: this is the mamba project's documentation: https://mamba.readthedocs.io/en/latest/

> Side note for this issue: what about having a channel= keyword argument for conda_install so that one could write channel="conda-forge" if selecting a channel? It would be a bit more natural than "--channel=conda-forge", I think, and likely is very common.

Probably makes sense to make a separate issue for this.

**Comment by henryiii** [comment]
Ahh, never mind, looking at the [usage](https://github.com/theacodes/nox/blob/bcaa5ffa42173037030f67e2ae58d10fbe659945/nox/sessions.py#L553), it could easily just be a regular argument / instance variable, I think.

The only question remaining is, would the "mamba" backend require mamba to be installed, or should it try to install mamba with conda if mamba is not installed? The first one (requiring it to be preinstalled) would be fine with me for a first iteration, and it could be extended later to install mamba if you wanted to add that?

**Comment by henryiii** [comment]
Xref: Mentioned as a side note in #346
