### ISSUE TITLE
conda: set channel via keyword

### ISSUE THREAD

**Issue by henryiii** [theacodes/nox#446]
**How would this feature be useful?**
Minor addition for a common situation.

**Describe the solution you'd like**

What about having a `channel=` keyword argument for `conda_install` so that one could write `channel="conda-forge"` if selecting a channel? It would be a bit more natural than `"--channel=conda-forge"`, I think, and likely is very common.

It is possible to set multiple channels - this is required for bioconda, for example. This could be an iterable, `channel=["conda-forge", "bioconda"]`. Maybe the keyword should be "channels" and always takes a list?

**Describe alternatives you've considered**

Leave as is.

**Comment by FollowTheProcess** [comment]
I think this is a good idea, I use conda a little bit and do sometimes run into difficulties with different channels. Having the flexibility to choose per session would be ideal.

I think this would be fairly easy to implement too as all you'd have to do (I think) is implement the argument here: https://github.com/theacodes/nox/blob/9c696e2bc2e47ec0f2acd322c7e4be941dab0518/nox/sessions.py#L342-L346

Then it effectively just shells out to conda here:
https://github.com/theacodes/nox/blob/9c696e2bc2e47ec0f2acd322c7e4be941dab0518/nox/sessions.py#L403-L412

So as long as conda supports the `-c` flag to set the channel then this could be easily done
