### ISSUE TITLE
sessions: empty list of default sessions could print help

### ISSUE THREAD

**Issue by henryiii** [theacodes/nox#465]
**How would this feature be useful?**

Sometimes I'd like for the "default" run of nox (with no sessions) to print a help dialog instead; say if there's no clear "default" like `["lint", "tests"]`.

**Describe the solution you'd like**

I'd differentiate between `nox.options.sessions = None` and an empty iterable, `nox.options.sessions = []`. The former would be the default, and would run all sessions. The latter would instead print the `nox -l` help if no sessions were passed - it would mean "no sessions". Currently, `nox.options.sessions = []` does exactly the same thing as `nox.options.sessions = None` and runs all sessions, which is clearly not what would be expected from setting an empty list here.

**Describe alternatives you've considered**

A special token or setting could be used, but since `nox.options.sessions = []` misbehaves currently, I think that would be a natural place to put it.

**Comment by FollowTheProcess** [comment]
@henryiii I like this idea, I think this combined with the recent addition of printing the noxfile docstring on `nox --list`(#459) could provide a nice "front page" for people new to nox in projects.

My only hesitation would be the look of `nox.options.sessions = []` is not immediately obvious what it does, perhaps a reserved word "list" or "help" or something might be clearer but then that might override users who have a nox session with those names.

Maybe a way to go might be a reserved word of "--list", this way we know there's no chance of clashing with a user's sessions (because it wouldn't be valid syntax" and `nox.options.sessions = ["--list"]` makes it clear what behaviour we'd expect?

**Comment by henryiii** [comment]
An empty list does tell you exactly what it _does_, it runs no sessions at all. The only "special" thing is that it prints out a list of possible sessions instead of just not doing anything at all when there's nothing to do, as that would be very boring. Currently, `[]` doesn't actually turn off all sessions, but instead triggers "all" sessions like `None` does.

The problem with a reserved word like `"--list"` is that it's slightly harder to find/remember (though not too bad, due to the fact it matches the argument, still something you have to learn though), it would be expected to be able to be combined (`["--list", "test"]` - should this be allowed?), and it would open up the door to adding the rest of the arguments to nox inside the `sessions` list; if you can add `--list`, why not the others? (Not that these are all bad things, but they are design decisions).

**Comment by FollowTheProcess** [comment]
> An empty list does tell you exactly what it _does_, it runs no sessions at all. The only "special" thing is that it prints out a list of possible sessions instead of just not doing anything at all when there's nothing to do, as that would be very boring. Currently, `[]` doesn't actually turn off all sessions, but instead triggers "all" sessions like `None` does.
> 
> The problem with a reserved word like `"--list"` is that it's slightly harder to find/remember (though not too bad, due to the fact it matches the argument, still something you have to learn though), it would be expected to be able to be combined (`["--list", "test"]` - should this be allowed?), and it would open up the door to adding the rest of the arguments to nox inside the `sessions` list; if you can add `--list`, why not the others? (Not that these are all bad things, but they are design decisions).

Ahh yeah okay, good points. Especially the one about including the other arguments, could easily see that one spiralling

**Comment by cjolowicz** [comment]
I feel this conflates two separate issues:

1. When `nox.options.sessions` is an empty list, no session should run by default.
2. When no session is selected, Nox should print something helpful. (Currently Nox just exits with code 3.)

See the function `verify_manifest_nonempty` for the second point. Before returning `3`, we should print something useful. Either this would be just a message that no session was selected, with a hint to invoke `nox --list` to learn what sessions are available. Alternatively, we could print a message that no session was selected, and then directly list the available sessions. The latter would require extracting the listing logic from `honor_list_request` into a separate function which can be called from both `honor_list_request` and `verify_manifest_nonempty`.

**Comment by FollowTheProcess** [comment]
@cjolowicz Makes perfect sense to me. I think the latter option is the better one but is slightly more work to implement

**Comment by henryiii** [comment]
I'm confused, I see the following options:

* `nox.options.sessions` is default, nothing passed: run all sessions
* `nox.options.sessions` is `[]`, nothing passed: run nothing, show --list
* `nox.options.sessions` is anything, anything _valid_ is passed, run whatever was passed
* `nox.options.sessions` is anything, anything _invalid_ is passed, exit with code 3.

The current implementation handles these. Passing an empty `-s` does nothing differently before or now.

**Comment by henryiii** [comment]
And it does print when it produces error code 3:

```console
$ nox -s nothing
nox > Error while collecting sessions.
nox > Sessions not found: nothing
```

**Comment by cjolowicz** [comment]
You would reach the "no sessions" case when filtering by keywords or pythons:

```
$ nox -k 'not foo'
$ nox -p 3.14159
```

Passing an invalid session name is currently a different error condition, handled in `filter_manifest`. We may want to handle this similarly though. It would be helpful to list sessions or mention `nox --list` here as well.

**Comment by cjolowicz** [comment]
We may want to consider that the session listing can make it hard to see the actual error message, which would be one of the following:

- You need to specify a session. (For the case where `nox.options.sessions` is an empty list.)
- The specified session was not found.
- The keywords did not match any sessions.
- There is no session for the Python version specified.

So this would be a reason to prefer a hint to run `nox --list`.

I think it would also be fine to print the session listing in the case where `nox.options.sessions` is an empty list, and print the hint for `nox --list` in the other cases. That would address your primary use case, while still avoiding that error messages are being scrolled out of sight in the cases where it matters most.

**Comment by henryiii** [comment]
As a package author, I want to show a list instead of running some default subset (or all) if a user doesn't know how to run a session. I'd be fine in nox added a little `No sessions selected. Please select a session with -s <session name>.\n` header.

Currently, ~~the empty session case is untouched~~. `nox -k nothing` does exactly what it did before, it prints nothing and returns an error code. Ahh, didn't try the `-p` one, `-k` is fine, but not `-p`, that is now printing a list. It's also grey, interestingly.

**Comment by henryiii** [comment]
Is there a way to get the original manifest?

**Comment by henryiii** [comment]
I think I have something working, just need to clean up the tests. I'm moving all failures to filter_manifest (there are already some there anyway), that's when it knows _why_ things are failing already.

**Comment by henryiii** [comment]
Adding `nox.options.sessions = []` to the main nox noxfile as a demo and trying some examples:

```console
$ nox -s nothing
nox > Error while collecting sessions.
nox > Sessions not found: nothing
$ nox -k nothing
nox > No sessions selected after filtering by keyword.
$ nox -p 1.23
nox > Python version selection caused no sessions to selected.
$ nox
sessions selected. Please select a session with -s <session name>.

Sessions defined in /Users/henryschreiner/git/software/nox/noxfile.py:

* tests-3.6 -> Run test suite with pytest.
* tests-3.7 -> Run test suite with pytest.
* tests-3.8 -> Run test suite with pytest.
* tests-3.9 -> Run test suite with pytest.
* tests-3.10 -> Run test suite with pytest.
* conda_tests-3.6 -> Run test suite with pytest.
* conda_tests-3.7 -> Run test suite with pytest.
* conda_tests-3.8 -> Run test suite with pytest.
* conda_tests-3.9 -> Run test suite with pytest.
* conda_tests-3.10 -> Run test suite with pytest.
* cover -> Coverage analysis.
* blacken -> Run black code formatter.
* lint
* docs -> Build the documentation.
```

(`--list` slightly broken, will fix!)
