### ISSUE TITLE
Some mechanism where users can share interesting sessions

### ISSUE THREAD

**Issue by FollowTheProcess** [theacodes/nox#471]
**How would this feature be useful?**

I'm willing to bet that there's quite a few nox users out there who are doing weird and wonderful things with their nox sessions, outside the more common sessions like run pytest, linting etc.

I think it would be a great learning resource if nox had some way of users sharing these novel sessions in some sort of "semi-official" way (i.e. not just in passing on a related issue etc.).

When I was first starting with nox and wanting to do more complex things that aren't listed in the docs (for good reason, you don't want main project docs cluttered with complex workflows), I took to finding random examples in different repos, and using nox's own noxfile as a guide.

**Describe the solution you'd like**

Some sort of central location (could be a separate repo in the style of the 'awesome-x' series of repos, some GitHub mechanism hosted here like discussions or something, or a section in the project docs) where users can contribute their weird and wonderful nox sessions. 

Think of it like a nox cookbook, a semi-official place where nox users can show their cool "recipes".

To be totally clear, I don't think it would be valuable to have this "cookbook" filled with "here's how you run pytest", the docs already cover this super well. This is more for users composing novel automations with nox.

I'd be happy to kick this off and contribute some of the more interesting sessions I've come across to get it started.

For example, I know [pipx](https://github.com/pypa/pipx/blob/master/noxfile.py) use their noxfile to interact with git in the process of releasing a new version. I've stolen this from them for my projects because it's awesome!

I've also set up a "dev" session for my noxfile projects that automates the entire local dev setup for a python project (creating a project-level virtualenv, installing the project and its dependencies, even configuring VSCode automatically).

I bet some people are doing much crazier things with their noxfiles! It would be great to collect some of these examples in a central place

**Describe alternatives you've considered**

I guess the alternative is just pointing to interesting use cases

**Comment by DiddiLeija** [comment]
I like the idea of a Nox "cookbook".

Another option would be the GitHub wikis, where users can write their amazing use cases.

**Comment by theacodes** [comment]
I'd be happy to see a "cookbook" or "common patterns" section in the doc. I
do not want to add a Wiki.

**Comment by DiddiLeija** [comment]
Yup, a cookbook sounds better. If I can help with something, just tell me :)

**Comment by DiddiLeija** [comment]
If you want, I can start to write a "cookbook" section. Just want to know if someone disagrees.

**Comment by theacodes** [comment]
Go for it!

**Comment by FollowTheProcess** [comment]
@DiddiLeija I've got a rough starter scaffold I've been working on in the background. Let me get that finished up and into a PR for review, just so we don't duplicate effort 👍🏻 

If the "cookbook" section is something we want to keep, it'll be a longer running thing that contributors can add to at any time in the future so plenty of chance to contribute!

**Comment by DiddiLeija** [comment]
> @DiddiLeija I've got a rough starter scaffold I've been working on in the background. Let me get that finished up and into a PR for review, just so we don't duplicate effort 👍🏻

Sorry, I didn't know. Post your PR, and if I have a way to improve it, I will tell you ;)

> If the "cookbook" section is something we want to keep, it'll be a longer running thing that contributors can add to at any time in the future so plenty of chance to contribute!

Excellent!
