### ISSUE TITLE
Question: Does nox need another maintainer?

### ISSUE THREAD

**Issue by FollowTheProcess** [theacodes/nox#473]
I've been using nox for a while and I absolutely love it, I use it for all of my personal projects and anything new I write at work has nox integrated from the ground up!

As such I'm pretty invested at this point and I'd love to be able to help out keeping it in tip top maintained condition. I've contributed a few small changes recently and really enjoyed the process, got great feedback and help from maintainers etc. 

But I've noticed that most of the recent maintenance and interaction with contributors that I can see is done by either @theacodes or @cjolowicz.

Just wanted to say I'd be more than happy to volunteer some time to help maintain nox if you guys need any additional help 🙂

**Comment by theacodes** [comment]
Hi Tom! Sure!

Things don't really change much when you're a maintainer - we'd still want you to have any PRs you author reviewed by at least one other maintainer. But, I'm happy to give you rights to manage issues and review & merge PRs. Feel free to add yourself to the list of maintainers in the docs. Don't hesitate to reach out if you're unsure about anything.

:)
