### ISSUE TITLE
Python 3.10.0-rc2 not behaving as expected on Github Actions

### ISSUE THREAD

**Issue by FollowTheProcess** [theacodes/nox#477]
**Describe the bug**
I happened to notice that the Github Actions 3.10.0-rc2 runs were always successful even when others failed, which prompted me to take a look and I discovered that they are successful because nox is simply skipping citing interpreter not found (see below).

<img width="925" alt="image" src="https://user-images.githubusercontent.com/62767721/133330583-a978d445-f828-49e0-b321-67421261474f.png">

I introduced this in #475 because I did the same on some personal projects and saw CI "passing" so thought nothing of it! 🤦🏻

I'll assign this to myself because I'll be sorting it out for my own projects anyway so I'll upstream the solution I find 👍🏻  

**How to reproduce**

Any 3.10.0-rc2 run on Github Actions should do this.

**Expected behavior**

Should have run nox with python3.10.

Edit: This seems to be because 3.10.0-rc.2 isn't encoded as such on the GHA runner:

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/62767721/133331873-0bc6319e-b7eb-427c-8111-da33c0cba81a.png">

So nox is doing exactly what it should be doing here and ignoring a missing interpreter. Should be a simple fix to the GHA file 🙂

**Comment by FollowTheProcess** [comment]
It's more to do with how we use it. We call nox and pass the `matrix.python_version` directly to `nox --session` which works as long as the python interpreter is located on the filesystem as the same path as it's identifier for the setup python action.

In the case of `3.10.0-rc.2` it's name does not match its path on the GHA runner so we'll have to handle this case, it'll just take some playing around to find the cleanest way of handling it.

**Comment by DiddiLeija** [comment]
Well, since you've separated the `build-py310` step from the others, you can directly tell Nox to use Python 3.10:

```yaml
        run: nox --non-interactive --session tests-3.10 -- --full-trace
```

This could be a workaround, until there's a final release for Python 3.10.

**Comment by DiddiLeija** [comment]
If you like this idea, tell me and I will post a PR to apply the changes.

**Comment by FollowTheProcess** [comment]
Yeah this would work. I've done this on my fork but unfortunately I think it could be more complex than that as we're now getting coverage failures (see [here](https://github.com/FollowTheProcess/nox/runs/3613749834?check_suite_focus=true)) so just trying to figure out why code might be uncovered on 3.10 but not on any other version.

**Comment by FollowTheProcess** [comment]
Closing in favour of #478
