### ISSUE TITLE
Expose a `warn` log to the session

### ISSUE THREAD

**Issue by FollowTheProcess** [theacodes/nox#481]
**How would this feature be useful?**

I often find myself using the `session.log` method in some of my more complex sessions to inform the user
what's going on.

I do use the `session.error` for failing things but occasionally I run into something that would be more suitable as a warning in the yellow text (e.g. warning if things are out of date etc.)

**Describe the solution you'd like**

Some way of logging a warning from within a session. This could be either a `session.warn` or maybe a `session.log("message", type="warn")` or something like that.

**Describe alternatives you've considered**

As far as I know there's no way of doing this currently (I could be wrong).

**Comment by DiddiLeija** [comment]
I'm interested on this! I like that idea. If this is going to be applied, I offer to work on it. Just tell me :)

**Comment by theacodes** [comment]
I'm totally cool with session.warn

**Comment by DiddiLeija** [comment]
Me too. I personally prefer `session.warn` instead of `session.log("message", type="warn")`.

**Comment by DiddiLeija** [comment]
Estupend! If no one disagrees with the idea, I will work on this.

**Comment by DiddiLeija** [comment]
I created #482. Review it whenever you want.
