### ISSUE TITLE
Add a `debug` function for the session logging

### ISSUE THREAD

**Issue by DiddiLeija** [theacodes/nox#485]
**How would this feature be useful?**

On #482, I introduced a `session.warn` functionality. Then, I started to use it on my local projects. And it works pretty fine! Now,
I would like to use... something like a `session.debug` method to expose "low errors".

**Describe the solution you'd like**

A `session.debug` function, or something similar.

**Describe alternatives you've considered**

N/A

**Comment by DiddiLeija** [comment]
What do you think? Can I work on this?

**Comment by theacodes** [comment]
Go for it
