### ISSUE TITLE
Allow hyphens as an alias for `_` from the CLI

### ISSUE THREAD

**Issue by choldgraf** [theacodes/nox#486]
**How would this feature be useful?**
I have an irrational preference for hyphens `-` over underscores (`_`) because they don't require me to hit the `shift` key 😅. BUT, I cannot use hyphens to name my jobs because my sessions need to be python functions!

**Describe the solution you'd like**
It would be great if hyphens were treated like underscores at invocation, so I could do `nox -s docs-build` and this would behave like `nox -s docs_build`.

**Describe alternatives you've considered**
Doing soul searching about why I hate using the `shift` key unnecessarily so much :-)  (seriously this isn't really that big of a deal, but thought I'd mention it as a small quality of life improvement if there's interest)

**Comment by DiddiLeija** [comment]
I tried to reproduce this, and I found that you can use hyphens using `@nox.session(name="name-with-hyphens")`:

My noxfile:

```python
import nox

@nox.session(name="name-with-hyphens")
def some_func(session):
    session.install("nox")
    session.run("nox", "--version")
```

My output:

```
C:/Users/Diego Ramirez>nox --sessions name-with-hyphens
nox > Running session name-with-hyphens
nox > Creating virtual environment (virtualenv) using python.exe in .nox\name-with-hyphens
nox > python -m pip install nox
nox > nox --version
2021.6.12
nox > Session name-with-hyphens was successful.
```

Can you try this, and tell us if it doesn't work?

**Comment by choldgraf** [comment]
omg it works! yessss thank you :-)

I should really read the docs more closely - maybe it would be helpful if "Session name" were something like "Custom session name"? Either way, I will close this!
