### ISSUE TITLE
Would you like to release a new Nox version?

### ISSUE THREAD

**Issue by DiddiLeija** [theacodes/nox#487]
Hi everyone,

I have noticed that the latest version of `nox` [was released on June, 13](https://github.com/theacodes/nox/releases/tag/2021.6.12). Since that, [we made some useful changes](https://github.com/theacodes/nox/compare/2021.6.12...main). So, I would like to ask: _Would you like to release a new version?_

I'm not a maintainer, but if I can help with something, please tell me ;)

**Comment by theacodes** [comment]
Done. :) https://github.com/theacodes/nox/releases/tag/2021.10.1

**Comment by DiddiLeija** [comment]
Thanks @theacodes! :D
