### ISSUE TITLE
Documentation: Is Python 2 still supported?

### ISSUE THREAD

**Issue by DiddiLeija** [theacodes/nox#491]
Hi everyone!

I was reading the docs and I found that [the documentation](https://nox.thea.codes/en/stable/config.html#configuring-a-session-s-virtualenv) included an example of setting Python 2.7 as the Python version for the virtualenv. As far as I know, Python 2 is not supported now. So maybe we should remove any reference to Python 2? Or am I misunderstanding something here?

**Comment by theacodes** [comment]
Nox itself can not run under Python 2.7, however, Nox can still create sessions using Python 2.7 as the interpreter version.

**Comment by DiddiLeija** [comment]
Oh, got it. Sorry for the noise?

**Comment by theacodes** [comment]
No worries!
