### ISSUE TITLE
Running with `--no-venv` causes `session.install` to use unexpected interpreter

### ISSUE THREAD

**Issue by rhoban13** [theacodes/nox#503]
**Describe the bug**
Running with `--no-venv` causes `session.install` to be invoked with the `python` executable found on `PATH`, not the one running `nox`.

**How to reproduce**
Running in an environment where the executables `python` and `python3.8` are distinct:
```console
$ which python python3.8
/usr/bin/python
/usr/bin/python3.8
```

My `noxfile.py` just installs `pytest`.  Running we obtain:

```
$ python3.8 -m nox --no-venv
nox > Running session validate
nox > python -m pip install pytest
nox > Command python -m pip install failed with exit code 1:
/usr/bin/python: No module named pip
nox > Session validate failed.
```

Ignore the "No module named pip", the point being it's invoking `/usr/bin/python`, not `/usr/bin/python3.8`.

**Expected behavior**
Documentation on [forcing-sessions-backend](https://nox.thea.codes/en/stable/usage.html?highlight=no-venv#forcing-the-sessions-backend) suggests this should run "on the current python interpreter (the one running nox)".

**Possible fix**
I suspect a fix could be applied in `Session.install` [here](https://github.com/theacodes/nox/blob/main/nox/sessions.py#L476) to use `sys.executable` instead of the string `"python".  I'm not certain what conditions we'd need to check beforhand (how to verify we aren't running in a venv).

**Comment by cjolowicz** [comment]
Thanks for reporting this!

> I suspect a fix could be applied in Session.install here to use sys.executable instead of the string `"python". I'm not certain what conditions we'd need to check beforhand (how to verify we aren't running in a venv).

That should work. You can check if `self._runner.venv` is an instance of `PassthroughEnv`, as that's the one that implements the `--no-venv` feature.

**Comment by theacodes** [comment]
I feel like invoking "install" without a virtual environment should be an
error, since all sorts of unexpected behavior can happen. If someone wants
to actually install something in the global python interpreter, they can
run pip install via session.run.

**Comment by rhoban13** [comment]
> I feel like invoking "install" without a virtual environment should be an error, since all sorts of unexpected behavior can happen. If someone wants to actually install something in the global python interpreter, they can run pip install via session.run.

I agree you typically shouldn't install things into the global python interpreter, however that doesn't seem  like it should be `nox`'s responsibility to validate.  This is basically why [pip --require-virtualenv](https://pip.pypa.io/en/latest/cli/pip/#cmdoption-require-virtualenv) exists, I tend to export `PIP_REQUIRE_VIRTUALENV` in most setups to check this.

**Comment by theacodes** [comment]
Okay, sure, but I still don't think Nox should have a footgun like this
that's only turned off if the user knows some arcane pip stuff. We could
raise a helpful error when trying to use install without a virtualenv,
something like:

> Session {name} does not have a virtual environment, so you can't use
session.install() since it would modify the global Python environment. If
you're really sure that is what you want to do, use session.run("pip",
"install", ...) instead.

**Comment by DiddiLeija** [comment]
Yup, an error message (or even just a warning) would be better than doing pip variable manipulations. If you want, in the next week I can post a PR to do this. We only need to sketch how the message should look like ;)

**Comment by cjolowicz** [comment]
I agree that `session.install` without a venv backend is dangerous, and it would be better to raise a helpful error here. However, this is a breaking change, and there are projects out there that rely on the current behavior (e.g. [here](https://github.com/drhagen/parsita/blob/master/noxfile.py)). This behavior was explicitly allowed in #316, see #318 and #301 for background. Should we go through a deprecation phase then?

**Comment by rhoban13** [comment]
https://github.com/theacodes/nox/issues/301 is exactly the use case I'm interested in.
