### ISSUE TITLE
Redundant license inclusion on MANIFEST.in

### ISSUE THREAD

**Issue by DiddiLeija** [theacodes/nox#504]
I was reading the `MANIFEST.in` file, and found this line:

https://github.com/theacodes/nox/blob/7443a93582a47a7dc680d90d6afeb686368e3985/MANIFEST.in#L1

However, https://packaging.python.org/guides/using-manifest-in/#how-files-are-included-in-an-sdist says that the license file defined by `license_file` (at `setup.cfg`) is included by default by newer versions of Setuptools. The `license_file` is:

https://github.com/theacodes/nox/blob/7443a93582a47a7dc680d90d6afeb686368e3985/setup.cfg#L11

I just want to know if the `MANIFEST.in` inclusion is redundant in our case, since I don't know how does `build` includes files. Also, if that's the case, I offer to open a PR to fix that.

**Comment by cjolowicz** [comment]
Thanks for catching that! We require setuptools > 42 in our pyproject.toml, so removing the line from MANIFEST.in should be safe.￼

**Comment by DiddiLeija** [comment]
Excellent! I'll post a PR in a few muntes.

**Comment by DiddiLeija** [comment]
I created #505 to fix this.
