### ISSUE TITLE
Missing copyright notices?

### ISSUE THREAD

**Issue by DiddiLeija** [theacodes/nox#507]
**Describe the bug**

I don't know a lot about the Apache License. But as far as I know, the code should contain a copyright notice, according to these
lines: https://github.com/theacodes/nox/blob/main/LICENSE#L189-L201

However, I just noticed that these files does not contain that notice:

- https://github.com/theacodes/nox/blob/e7ae509ac1b46820953cb8a5793c95d47070928c/nox/_decorators.py
- https://github.com/theacodes/nox/blob/e7ae509ac1b46820953cb8a5793c95d47070928c/nox/_typing.py

**How to reproduce**

Just browse the files above. They don't contain a copyright notice like the others (see https://github.com/theacodes/nox/blob/e7ae509ac1b46820953cb8a5793c95d47070928c/nox/sessions.py for an example).

**Expected behavior**

I don't know if this is a bug at all. I expected the copyright notices in those files. But maybe it's my mistake, I'm not sure.

**Comment by DiddiLeija** [comment]
Since this is a license/copyright issue, I want to know @theacodes opinion.

**Comment by theacodes** [comment]
Sure, they should be added.

**Comment by DiddiLeija** [comment]
Ok. Can I work on it? Or would you like to do it? Also, I noticed that the existing notices have different dates: 2016, 2017, 2019... Is that ok?

**Comment by theacodes** [comment]
Yes, the date is the date of original publication.

**Comment by DiddiLeija** [comment]
Ok. If you agree, the next week I'll investigate the publication date of the missing files, and post a PR to add the copyright notices. Of course, if you don't disagree :smile:.

**Comment by theacodes** [comment]
Totally fine with me 🙂

**Comment by DiddiLeija** [comment]
@theacodes, I created #509 to fix this. Please review it and tell me if I should add the copyright in another place :smiley:.
