### ISSUE TITLE
Convenience method to install nox as git pre-commit hook

### ISSUE THREAD

**Issue by ktbarrett** [theacodes/nox#515]
**How would this feature be useful?**
I often write "check" tasks which I like to run as a pre-commit hook. I modified a pre-commit (the tool) generated file to handle this that I reuse and modify for each project. It would be nice if generating and installing a pre-commit hooks to run a particular session was built into the tool.

The pre-commit hook I use that I modified from pre-commit (tool)'s hook.
```bash
#!/usr/bin/env bash

# start templated
INSTALL_PYTHON=/path/to/my/python
SESSION=check
# end templated

if [ -x "$INSTALL_PYTHON" ]; then
    exec "$INSTALL_PYTHON" -m nox -s "${SESSION}"
elif command -v nox > /dev/null; then
    exec nox -s "${SESSION}"
else
    echo '`nox` not found.  Did you forget to activate your virtualenv?' 1>&2
    exit 1
fi
```

**Describe the solution you'd like**
Ideally there would be a pair of pre-commit install/uninstall commands. Something like
```
nox --install-precommit=check
nox --uninstall-precommit
```

**Describe alternatives you've considered**
Doing it manually... Not sure what else. I'm not that creative :grin:

**Comment by cjolowicz** [comment]
Why not leverage [pre-commit](https://pre-commit.com) itself? You can drop a `.pre-commit-config.yaml` like this into your project:

```yaml
repos:
  - repo: local
    hooks:
      - id: nox
        name: Nox
        entry: nox -s check --
        language: system
        types: [python]
        require_serial: true
```

You can install the pre-commit hook using `pre-commit install`.

Here's an example noxfile.py you could use with this:

```python
import nox

@nox.session
def check(session):
    session.install("flake8")
    session.run("flake8", *session.posargs)
```

Here `pre-commit` will invoke Nox with the Python files staged for each commit, and Nox will forward them to Flake8. (Obviously if this is *all* you do, you should just use plain pre-commit with flake8.) I'd probably avoid hardcoding the session name in the `.pre-commit-config.yaml` though, and either run all sessions in noxfile.py, or define `nox.sessions` in the noxfile.py, and/or define `NOXSESSION` in the environment as needed.

Personally, I prefer to integrate Nox and pre-commit in the opposite direction, with a Nox session that installs and invokes pre-commit. But to each their own :)

**Comment by ktbarrett** [comment]
> Why not leverage pre-commit itself?

I am well aware of pre-commit. Running nox per-file will be a huge overhead. It's just not a reasonable solution. 

> Obviously if this is all you do, you should just use plain pre-commit with flake8

Exactly...

>I prefer to integrate Nox and pre-commit in the opposite direction, with a Nox session that installs and invokes pre-commit. But to each their own :)

That makes no sense to me.

The whole point is to replace pre-commit with nox, since it really wouldn't take much effort, there is a lot of overlap in functionality, and nox being the more capable tool. I'm also trying to avoid pre-commit's decision to only run checks *per file* which is just not how mypy was intended to be run and causes a number of problems. I want to avoid complicating my project and avoid specifying tools and flow in multiple places by using a less capable tool *in addition to* nox.

**Comment by cjolowicz** [comment]
> Running nox per-file will be a huge overhead. 

I'm not sure I understand which overhead you refer to, can you elaborate?

In the example I gave, Nox is invoked once per commit, with files passed on the command-line after the `--` separator. It should run somewhat faster than what you proposed above, by virtue of linting only files touched by the commit.

> The whole point is to replace pre-commit with nox, since it really wouldn't take much effort, there is a lot of overlap in functionality, and nox being the more capable tool.

The effort may be small if we limit git integration to the specific use case you presented above. But pre-commit covers much more ground than that. People would soon expect us to support additional requirements, for example other hooks like pre-push or commit-msg, passing and filtering files touched by the commit, or stashing local modifications. They'd be better off just using pre-commit. As a mature tool specializing in git hook management, it has had time to address a myriad of edge cases.

> I'm also trying to avoid pre-commit's decision to only run checks _per file_ which is just not how mypy was intended to be run and causes a number of problems.

I also find that running mypy from Nox has some advantages (see #516). Would it be an option for you to only run linters on pre-commit, and keep mypy as a plain Nox session?

If you do need to run mypy as a pre-commit hook as well, I can see two options: 

1. Run the Nox session from pre-commit as described above. 
2. Use a standard mypy pre-commit hook in addition to the Nox session.

The first option will produce more consistent results. The second option has the advantage of simplicity and speed. There won't be much duplication if you keep the mypy configuration in pyproject.toml or mypy.ini.

> I want to avoid complicating my project and avoid specifying tools and flow in multiple places by using a less capable tool _in addition to_ nox.

You don't need to. My advice would be this: Run linters from pre-commit, and run pre-commit from Nox. Run mypy from Nox only. You'll still have Nox as a single entry-point, and no duplication or complexity.

I certainly wouldn't consider pre-commit "less capable" in any way. Nox and pre-commit have different goals, and complete each other nicely.

**Comment by henryiii** [comment]
> pre-commit's decision to only run checks per file

This is not a decision pre-commit makes, it's one you make. Set `pass_filenames: false` on a hook that needs to run once instead of per-file. Done.

> nox being the more capable tool

This is not remotely true. They are _different_ tools. pre-commit can run any check, and fully locks dependencies, and auto-updates, and so much more.

From https://scikit-hep.org/developer/tasks:

```python
@nox.session
def lint(session: nox.Session) -> None:
    """
    Run the linter.
    """
    session.install("pre-commit")
    session.run("pre-commit", "run", "--all-files", *session.posargs)
```

And use https://scikit-hep.org/developer/tasks for some setup. The setup there is fine for MyPy, IMO, but you can add `pass_filenames: false` if you want.

Or you can also leave mypy as nox only if it's too slow. I like the pinning, etc, that pre-commit provides.

**Comment by cjolowicz** [comment]
Closing as it seems unlikely at this point that we'll support pre-commit hook installation in Nox.

Feel free to continue the discussion though. One tool commonly used with pre-commit that also offers its own hook implementation is [isort](https://pycqa.github.io/isort/docs/configuration/git_hook.html). So if we changed our mind, we'd probably want to take a look there. Note that isort is not in the business of installing hooks, it just offers a Python API that can be used to craft your own hook.

**Comment by ktbarrett** [comment]
I understand people may ask for more features and I tend to agree that I don't like increasing project scope like that. Feature implementation is always up for discussion. And this is not an argument about whether pre-commit or nox are valid tools. In my case, the only value that pre-commit brings is the installation of git hooks. Using 2 tools when one would do is not an advantage. pre-commit doesn't just install hooks, but always adds itself as a layer of indirection and necessary configuration. It would be nice if pre-commit didn't try to duplicate functionality, or at least split it up. Every tool seems to be it's own ecosystem rather than working together. There is an effort in the EDA space to try to unify all these disparate tools. I'm surprised that there isn't such a push against the proliferation of tools in Python. I'd prefer to only use nox and have some way to bridge the feature gap. Or use pre-commit in a way where there isn't redundancy, coupling, or stepping on toes. 

Some additional thoughts since both posts were long
* I don't need additional kinds of it hooks, only pre-commit
* generating a hook file the user manages, like what isort supports, sounds like a good idea
* Version pinning can be accomplished with requirements files and tools like pip-upgrader
* `pass_filenames: false` is an unintuitive name since I don't know how pre-commit is implemented
* `pass_filenames: false` is still not sufficient since it still runs on all unstaged or untracked changes. I still need to run mypy in nox to stash changes
* nox is just Python, so it is a more capable automation tool, and the way nox is instrumented is simple (as in lower conceptual overhead)

Of course this feature doesn't have to be implemented in this project either. It's entirely possible to do externally. I may pursue that option.

**Comment by henryiii** [comment]
* isort natively supports pre-commit (the tool) too, by the way.


> `pass_filenames: false` is an unintuitive name since I don't know how pre-commit is implemented

Can't this be used to argue against anything?

> pass_filenames: false is still not sufficient since it still runs on all unstaged or untracked changes

No it does not. Pre-commit carefully handles partial stages and untracked changes. Nox would not unless it duplicated all of this functionality - there's a ton of work to make pre-commit work well, and you are asking for that to be duplicated in nox, IMO.

> nox is just Python

pre-commit is just Python too (in implementation).

What do you want from a pre-commit hook? I assume it needs to be fast. pre-commit does a lot to make sure it is caching and running as fast as it possibly can. Nox, on the other hand, isn't trying to be fast by default.

Also, I've never had to turn off the default pre-commit pass filenames for mypy, and my mypy runs are under a second or two on over a dozen different projects. Nox can't even create a venv in that amount of time. I think it's different tools for different tasks.

**Comment by ktbarrett** [comment]
> Can't this be used to argue against anything?

I was pointing it out since I have seen this a number of times where names/descriptions are chosen whose meaning is tied to the implementation a user might not know. I skip over them because I don't understand what they actually mean so I presume it's some advanced feature. But it turns out to be a very useful feature, even to novices. It's frustrating. Perhaps it's just a mistaken presumption it being an "advanced" feature?

Changes can have second order effects on other files, so certain checks should be run over the whole project every time. Type checking with mypy is just one example of that. `pass_filenames` should be a switch with a name/description that newbies can understand, or at least be understood by first explaining how hooks are called.

> Pre-commit carefully handles partial stages and untracked changes

I swear I tried it when you mentioned it first and mypy was checking untracked files. But I just tried it again and it does not. WTF :sob: 

> pre-commit is just Python too

No it's a declarative DSL. You are strictly limited to the provided feature set. If it does not suffice you must either beg for the addition of an extra knob, or work around the problem in some potentially obtuse way. I'm really not a fan of declarative automation tools in general. I've moved away from tox to nox for exactly that reason. We have an automation tool at work that uses YAMLs to describe build flows and it's become such a problem with the limited expressivity and additional maintenance effort of that format that we just hacked a programming language on top of it. 

> I've never had to turn off the default pre-commit pass filenames for mypy

Correct me if I'm wrong, but it seems like you may be missing issues if you do this. Make a change in one module, downstream modules in your project may break, but they may not be checked.

**Comment by ktbarrett** [comment]
Looks like I may have been partially correct about pre-commit not handling untracked changes. When running with `pass_filesname: false` it isn't stashing the `build/` directory which contains a copy of the source code, which then confuses mypy. It does handle partial staging on the same file though. Seems like they missed a few details.
