### ISSUE TITLE
Conda tests session should skip rather than fail if conda not installed

### ISSUE THREAD

**Issue by FollowTheProcess** [theacodes/nox#520]
**Describe the bug**

While quickly doing #519, I noticed that running bare `nox` on my machine results in somewhat unattractive looking failures:

<img width="709" alt="image" src="https://user-images.githubusercontent.com/62767721/147132932-80c1d7df-7904-4df4-a08a-a38aa821c78a.png">

I think a better solution would be to first check if the user has `conda` and skip this session if not (much like the tests themselves have a `pytest.mark.skipif` condition.

**How to reproduce**

Run `nox` on this project without having conda installed.

**Expected behavior**

Should skip `conda_tests` if conda is not installed.

This is a super quick fix and I'll do it now, filing the issue for traceability 🙂

**Comment by DiddiLeija** [comment]
I can reproduce this using Windows. I think skipping `conda_tests` could be useful. Actually, we can add something to `nox.session` to add a conditional to skip sessions?

**Comment by FollowTheProcess** [comment]
@DiddiLeija Yeah potentially, something like

```python
if <something that would render the session useless>:
    session.skip(reason="Missing something needed for the session")
```

Kind of like pytest's `mark.skipif`.

I think this could be a bit complex to implement though and might be better served with the simple `nox.options.sessions` filter?

**Comment by DiddiLeija** [comment]
> something like
> 
> ```python
> if <something that would render the session useless>:
>     session.skip(reason="Missing something needed for the session")
> ```
> 
> Kind of like pytest's `mark.skipif`.

Yup. I'm looking for something like that.

> I think this could be a bit complex to implement though and might be better served with the simple `nox.options.sessions` filter?

I will take a closer look for this idea later, probably next year.

**Comment by FollowTheProcess** [comment]
@DiddiLeija I've just found out `session.skip` is already a thing!
