### ISSUE TITLE
Dropping support for python 3.6 EOL?

### ISSUE THREAD

**Issue by FollowTheProcess** [theacodes/nox#525]
Obviously no real rush for this, but as today marks the official [EOL Date](https://endoflife.date/python) of python 3.6 I thought we should track it/discuss how to proceed.

Perhaps add a deprecation warning first in the next release and then drop support in the next one, or just straight drop 3.6?

**Comment by cjolowicz** [comment]
I think we can drop Python 3.6, no need for a deprecation.

(And to be clear, this about installing Nox on Python 3.6. Nox will still create and run sessions on old Pythons.)

**Comment by DiddiLeija** [comment]
I'll take this. And I agree with @cjolowicz, we won't need a warning.
