### ISSUE TITLE
Do the `lint`, `docs` and `blacken` sessions really need to be pinned to specific pythons?

### ISSUE THREAD

**Issue by FollowTheProcess** [theacodes/nox#531]
In our noxfile, the `lint`, `doc`, and `blacken` sessions are pinned to specific pythons using:

```python
@nox.session(python="3.9")
```

As recently discovered (and quickly fixed! #529 Thanks @henryiii) this caused linting and docs building to quietly "pass" on GitHub actions (see [here](https://github.com/theacodes/nox/runs/4623345258?check_suite_focus=true)).

I can recall this happening once before too (however I can't seem to find it now).

The pinning of these sessions also causes a contributor to have to use `--force-python` if they don't have the specific version that the sessions are pinned to.

I think the best way to ensure a high quality contributing experience is for any contributor to be able to simply run `nox` and if everything passes, they can be confident that the CI for their contribution will pass. Implicitly skipping some of the sessions might get in the way of this goal.

If there is no specific reason these sessions are pinned I would suggest changing their session decorators to simply `@nox.session` to allow them to run under the default python (as the `cover` session is already).

If however there is a reason, I suggest we edit the CI to use the `--error-on-missing-interpreters` switch so that these sessions cannot silently "pass" without running.

Thoughts?

**Comment by cjolowicz** [comment]
For the docs session, prioritizing ease of contributing over a deterministic CI makes sense to me.

I'm less sure about the lint and blacken sessions. Flake8, mypy, isort, and black parse the Python AST. So it seems best to run them a well-defined version of Python, and probably the latest stable version. I agree that `--error-on-missing-interpreters` is a good idea for CI in this case.

**Comment by henryiii** [comment]
Flake8, mypy, isort, and black all do try to be as consistent as possible. They might not support newer syntax from an older version, like 3.10+ only syntax when running on 3.9, but nox explicitly does not have anything that doesn't run on 3.6+ (soon 3.7+), so the runs should be exactly identical on 3.6+. I've never had an issue with avoiding pins for linters, and it is rather irritating to have the linting job fail and require you to install a specific Python version.
