### ISSUE TITLE
Open discussions, gitter, something

### ISSUE THREAD

**Issue by ktbarrett** [theacodes/nox#534]
**How would this feature be useful?**
Issues only have "feature request" or "bug report" format, no question format; so I assume issues are not for questions. Github discussions are disabled. There is no gitter or discord linked. So, where are questions or discussions about nox supposed to occur?

**Describe the solution you'd like**
I would like to see a gitter or discord. I participate in and moderate a few gitter channels and really enjoy interactive problem solving, tangent discussions, and general sense of community that comes from that.

**Describe alternatives you've considered**
StackOverflow has a nox tag, but it is solely short Q&A format and can be pretty toxic, but it is searchable. Github Discussions can be free-form or Q&A format, they are searchable, and integrate with Github; however, in my experience people tend to not understand how to use it correctly (maybe this is a UX problem?).

**Comment by theacodes** [comment]
We can use the Winterbloom discord, since I'm considering moving Nox over to github.com/wntrblm so it's easier to manage the contributors and notifications.

I'll make a #nox channel and y'all can mute notifications for everything else if you want.

https://discord.gg/D35cxRxc

**Comment by DiddiLeija** [comment]
> I'm considering moving Nox over to github.com/wntrblm so it's easier to manage the contributors and notifications.

And... it happened :partying_face:

> https://discord.gg/D35cxRxc

Seems like this invite became invalid (or expired? [^1]). @theacodes, could you check if this invite is still functional, and provide a new one if not? That way, more people with intentions of joining will be there [^2].

[^1]: I suspect the invite expired (but maybe I'm wrong). Maybe a new invite without expire date is the solution?
[^2]: Also, what about mentioning this in the docs? Or maybe in the project's README? Maybe somewhere else?

**Comment by FollowTheProcess** [comment]
Just further to this, as part of #600 I'm looking at including a link to the discord in the issue form config so it shows up as a method to ask a more general question not covered by the more rigid bug/feature forms. Much like [pip](https://github.com/pypa/pip) do here with IRC:

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/62767721/165463110-70d0297e-5f62-4909-b84f-426fcf7d800f.png">

Is it possible to have a permanent invite link to the discord? If not this approach may not work as intended as we'd have to keep refreshing the link.

**Comment by DiddiLeija** [comment]
> Is it possible to have a permanent invite link to the discord? If not this approach may not work as intended as we'd have to keep refreshing the link.

When creating a Discord invitation, you can select the expire date. Check this example [^1]:

<img width="328" alt="image" src="https://user-images.githubusercontent.com/83621221/165542289-f16d10f3-42b5-41ce-88f3-5aa480b45783.png">

In the red circle, there's an "edit invite settings" button. When clicking it, you'll find a seting to modify the expire date,
or set the invite to be permanent.

I would personally prefer a permanent invite. Since we are humans, we could easily forget to update it :sweat_smile:

[^1]: My Discord works in Spanish, so please forget that.

**Comment by FollowTheProcess** [comment]
In that case then, I'll remove the question form from #600 and then when we get the permalink for discord we can put that in the config.yml. I'll put a ref to this in #600 to continue because this issue is closed

**Comment by theacodes** [comment]
Hey folks, here's a permalink for the discord: https://discord.gg/C5EH3N3fsk

If y'all would prefer github discussions, I can enable that. Just let me know.
