### ISSUE TITLE
Weird GHA failures on pull requests

### ISSUE THREAD

**Issue by DiddiLeija** [theacodes/nox#540]
This issue is mainly for tracking strange recent issues with GHA and our CI. This affected our pull requests.

Failing PRs I know:

- #526 
- #537
- https://github.com/theacodes/nox/pull/538#issuecomment-1001550911

**Comment by Tolker-KU** [comment]
As @henryiii pointed out this was probably related to an incident on Github's side. See https://www.githubstatus.com/incidents/gh0vvxtlj5v7. As it is closed now I think we can close this issue?
