### ISSUE TITLE
Strange lint CI failure?

### ISSUE THREAD

**Issue by FollowTheProcess** [theacodes/nox#545]
**Describe the bug**

Noticed a lint job failure after merging #543 (which had no such failure on the PR):

See [here](https://github.com/theacodes/nox/runs/4649987680?check_suite_focus=true)

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/62767721/147565500-a1658b05-f749-4071-a351-65d51af9e479.png">

I tried re-running but got the same outcome, then on my fork I tried adding `python -m pip install --upgrade pip setuptools wheel` to all CI jobs but got the same [outcome](https://github.com/FollowTheProcess/nox/runs/4650005563?check_suite_focus=true)

Edit: Also tried injecting setuptools directly into the nox session with `session.install("setuptools", "pre-commit")`, same result

Edit2: It seemed to always happen on `isort` so I tried removing it from the pre-commit config but it then just failed on `black` with the exact same error

**How to reproduce**

Look at the CI lint job, it seems to happen on re-runs

**Expected behavior**

Should run to success like in the PR

**Comment by cjolowicz** [comment]
I could only skim through them, but the failure may be related to these  issues:

- https://github.com/pypa/setuptools/issues/2353
- https://github.com/pypa/pip/issues/6264#issuecomment-685230919

Would updating setuptools in the runner's Python installation help?

```
python -m pip install -U setuptools
```

I'm assuming here that `which python` prints `/opt/hostedtoolcache/Python/3.9.9/x64/bin/python`, as that's the runner's Python installation. Maybe add that line to the workflow when testing.

**Comment by FollowTheProcess** [comment]
> I'm assuming here that which python prints /opt/hostedtoolcache/Python/3.9.9/x64/bin/python, as that's the runner's Python installation. Maybe add that line to the workflow when testing.

Yep!

I tried `python -m pip install -U setuptools` too to no avail: [here](https://github.com/FollowTheProcess/nox/runs/4650346937?check_suite_focus=true)

Very strange

**Comment by cjolowicz** [comment]
> I tried `python -m pip install -U setuptools` too to no avail: [here](https://github.com/FollowTheProcess/nox/runs/4650346937?check_suite_focus=true)

You need to invoke this outside of the virtualenv created by Nox.

Alternatively, use the full path:

```
/opt/hostedtoolcache/Python/3.9.9/x64/bin/python -m pip install -U setuptools
```

**Comment by cjolowicz** [comment]
Sorry I didn't see you were already doing this.

**Comment by FollowTheProcess** [comment]
There was a new release of [virtualenv](https://github.com/pypa/virtualenv/blob/main/docs/changelog.rst#features---20110) today which bumped the embedded version of setuptools, that's next on my list!

**Comment by FollowTheProcess** [comment]
It looks like virtualenv is the culprit! See my now passing lint run [here](https://github.com/FollowTheProcess/nox/runs/4650479594?check_suite_focus=true)

Pinning virtualenv to 20.10.0 inside the lint session has fixed it.

[pre-commit](https://github.com/pre-commit/pre-commit/blob/16f68254a84df8d69431bab2ba410770746b95bd/setup.cfg#L32) depends on `virtualenv>=20.0.8`

So it must have pulled in today's `20.11.0`, I guess they released it in between the PR and the CI run after the merge.

virtualenv 20.11.0 bumps the embedded setuptools from 58.3.0 to 59.4.0 so I guess there is a breaking change in there somewhere. Weird that I couldn't reproduce locally though, even with these versions
