### ISSUE TITLE
Bump setuptools in pyproject.toml to >=51.0.0?

### ISSUE THREAD

**Issue by FollowTheProcess** [theacodes/nox#553]
**Describe the bug**

While doing some digging in the setuptools documentation I came across this section: https://setuptools.pypa.io/en/latest/userguide/declarative_config.html#options which (if I'm reading it correctly) suggests that in order to use the `options.entry_points` key (as we do in our `setup.cfg` [here](https://github.com/theacodes/nox/blob/8b12711d43a4c7b231c18c9b124501e4d23d5b53/setup.cfg#L51)), you must use setuptools >= 51.0.0.

Currently we specify setuptools >= 42 in `pyproject.toml` [here](https://github.com/theacodes/nox/blob/8b12711d43a4c7b231c18c9b124501e4d23d5b53/pyproject.toml#L3)

If this is correct and I'm not reading it wrong, does this mean we could get a broken install if someone uses setuptools < 51?

Given that no one (to my knowledge) has raised an issue about this I think it's safe to assume no one has fell foul of this, but it seems like something we should fix?

**Comment by DiddiLeija** [comment]
I agree. I don't know if we'll break something in the process, though.

**Comment by henryiii** [comment]
What the... Pretty sure this is not new in [51](https://setuptools.pypa.io/en/latest/history.html#v51-0-0). It's been around as long as I can remember.

**Comment by henryiii** [comment]
Thinking they meant to put "41" not "51", perhaps.

**Comment by layday** [comment]
Pretty sure that existed even before 41. In fact it appears to have been there in the very first version of `setup.cfg`: https://github.com/pypa/setuptools/pull/862.

**Comment by cjolowicz** [comment]
Closing as per https://github.com/theacodes/nox/issues/553#issuecomment-1008277811, thanks @layday
