### ISSUE TITLE
Session().python is None when Session() is using the same interpreter as Nox

### ISSUE THREAD

**Issue by gschaffner** [theacodes/nox#558]
Hi! Thanks for sharing this great software.

**Describe the bug**
It would be useful if `Session().python` was set even when the `@session` decorator did not receive an argument for `python` or `py`. I am not sure if this should be categorized as a bug or a feature request, however, as `Session().python` is currently documented as

https://github.com/theacodes/nox/blob/386659e446aacdd681b5e1f25db6a2c03180a287/nox/sessions.py#L185

Related to this is that `@session` behaves the same with either `python=False` or `venv_backend="none"`, but different `@session` args here produce a different `Session().python`.

**How to reproduce**
Minimal working example:

```python
import nox


@nox.session
def foo(session):
    session.run("python", "-V")
    print(f"{session.python=}")
```

```console
$ python3.10 -m nox
nox > Running session foo
nox > Creating virtual environment (virtualenv) using python3.10 in .nox/foo
nox > python -V
Python 3.10.0
session.python=None
nox > Session foo was successful.
```

**Expected behavior**
`session.python == "3.10"` or `"python3.10"`, although my vote is for `"3.10"`.

**Comment by gschaffner** [comment]
The following would give the behavior proposed above:

```patch
diff --git a/nox/manifest.py b/nox/manifest.py
index ccbd08c..12faf52 100644
--- a/nox/manifest.py
+++ b/nox/manifest.py
@@ -208,10 +208,11 @@ class Manifest:
             or func.venv_backend
             or self._config.default_venv_backend
         )
-        if backend == "none" and isinstance(func.python, (list, tuple, set)):
-            # we can not log a warning here since the session is maybe deselected.
-            # instead let's set a flag, to warn later when session is actually run.
-            func.should_warn[WARN_PYTHONS_IGNORED] = func.python
+        if backend == "none":
+            if isinstance(func.python, (list, tuple, set)):
+                # we can not log a warning here since the session is maybe deselected.
+                # instead let's set a flag, to warn later when session is actually run.
+                func.should_warn[WARN_PYTHONS_IGNORED] = func.python
             func.python = False
 
         if self._config.extra_pythons:
diff --git a/nox/sessions.py b/nox/sessions.py
index a169396..0f360b4 100644
--- a/nox/sessions.py
+++ b/nox/sessions.py
@@ -182,8 +182,22 @@ class Session:
 
     @property
     def python(self) -> Optional[Union[str, Sequence[str], bool]]:
-        """The python version passed into ``@nox.session``."""
-        return self._runner.func.python
+        """The python version passed into ``@nox.session``.
+
+        If no python version was passed into ``@nox.session`` and
+        ``venv_backend='none'`` was also not passed to ``@nox.session``, this
+        version will be detected automatically. If ``venv_backend='none'`` was
+        passed, however, this version will be False.
+        """
+        if self._runner.func.python is None:
+            version_str = ".".join(map(str, sys.version_info[:2]))
+            imp_name = sys.implementation.name
+            if imp_name == "cpython":
+                return version_str
+            else:
+                return imp_name + version_str
+        else:
+            return self._runner.func.python
 
     @property
     def bin_paths(self) -> Optional[List[str]]:
@@ -641,7 +655,7 @@ class SessionRunner:
             or self.global_config.default_venv_backend
         )
 
-        if backend == "none" or self.func.python is False:
+        if self.func.python is False:
             self.venv = PassthroughEnv()
             return
```

This passes current tests on 3.9. Due to unfamiliarity with the codebase I am not sure if this is the best approach though---let me know, I am curious!

The version string finding implemented above was tested manually on CPython 3.10.0 and PyPy 3.8-7.3.7. I didn't test any other implementations as I was not sure what the standard for their version strings is---are they all meant to be interpreter filenames like they are for CPython and PyPy?

The version-finding might also be moved into `make_session` to keep things a bit closer together.

I'd like to open a PR with this patch if this looks good, or change it up and PR if doing so is within the ability of a first-time contributor to nox. I haven't yet figured out where to add test coverage for this and could use a hint there, though. To test this for e.g. PyPy without having to add new CI running PyPy, it seems that some of `sys` would need to be monkeypatched, which seems a bit scary.

**Comment by cjolowicz** [comment]
Thanks for the report!

I'm wondering, why not just use `sys.version_info` in your noxfile?

`session.python` behaves as designed and documented: it returns what was passed into the `@session` decorator.

If we change it to actively identify the interpreter (but only when `None` was passed), I see a few issues:

1. We break backwards compatibility: The function no longer returns `None`, so now it cannot be used to determine that the session uses the Nox interpreter. (Note that the session interface is not only used in trivial session functions where this would be obvious. Session functions can also call into other modules passing their session object.)
2. The behavior is inconsistent, because the function attempts to identify the interpreter only when the user didn't pass anything. For example, if the user passes `python="python"`, we'll still get the user-provided string.
3. The behavior isn't well specified because there's not a clear unique way to identify the interpreter implementation and version. In particular, it's hard to return a string that would also work as an explicit argument to `@session`.

**Comment by gschaffner** [comment]
This all makes sense, thanks!
