### ISSUE TITLE
Specify working directory for a session

### ISSUE THREAD

**Issue by RobertCraigie** [theacodes/nox#562]
**How would this feature be useful?**

I'm using nox to handle running benchmarks for multiple database clients, each in their own session (for easy parallelization and dependency management). The benchmarks and supporting files for each database client are in their own directory, this means I have to write my sessions like so:

```py
@nox.session()
def prisma(session: Session) -> None:
    with chdir('prisma'):
        ...

@contextmanager
def chdir(directory: str) -> Iterator[None]:
    cwd = os.getcwd()

    try:
        os.chdir(directory)
        yield
    finally:
        os.chdir(cwd)
```

**Describe the solution you'd like**

```py
@nox.session(chdir='prisma')
def prisma(session: Session) -> None:
    ...
```

**Describe alternatives you've considered**

Alternative is manually changing the directory (shown above), the ability to set a working directory for a session is merely QOL.

**Comment by Tolker-KU** [comment]
The context manager solution is already a feature in Nox. See [the docs](https://nox.thea.codes/en/latest/config.html#nox.sessions.Session.chdir). 

It is maybe not as elegant as being able to specify the working directory in the session decorator, but it gets the job done in a more flexible way.

**Comment by RobertCraigie** [comment]
Ah I didn't know of that solution, thank you :)

I do think the solution I've proposed would still be a nice quality of life improvement.

**Comment by FollowTheProcess** [comment]
Hi @RobertCraigie, thanks for the idea! The session decorator is probably one of the hardest working things in Nox currently and I think we're hesitant to add further complexity to it, particularly when the requested functionality is available in other ways (the context manager mentioned by @Tolker-KU) which was a great recent addition!

Not to say we'll never do this in the future but it's probably best to use the more flexible context manager for this functionality so I'm going to close this issue but thanks again for your input!
