### ISSUE TITLE
Support argcomplete v2.0

### ISSUE THREAD

**Issue by jwodder** [theacodes/nox#563]
Version 2.0.0 of [argcomplete](https://github.com/kislyuk/argcomplete) is out, yet nox limits the version it depends on to <2.  Please support argcomplete v2.0 so that users can use the latest versions of all involved packages.

**Comment by FollowTheProcess** [comment]
Hi @jwodder thanks for bringing that up. It looks (on a quick scan of the release notes) like the only "breaking" change is dropping support for python 2.7 and 3.5 so I'm sure nox could incorporate this as our minimum python is 3.6 at the moment (potentially soon to be 3.7).

If you want to throw in a PR for this, feel free

**Comment by zachliu** [comment]
sorry for commenting on a closed thread
when can we have this in a new release? :sweat_smile:
