### ISSUE TITLE
Consider a `.[dev]` optional extra in `setup.cfg`

### ISSUE THREAD

**Issue by FollowTheProcess** [theacodes/nox#570]
**How would this feature be useful?**

When developing against nox, I like to create a virtual environment and install the project in editable mode with all the linters and formatters etc. so VSCode helps me out with mypy and things like that. Currently I do something along the lines of:

```shell
python -m venv .venv
source .venv/bin/activate.fish

python -m pip install --upgrade pip setuptools wheel
python -m pip install -e .
python -m pip install -r requirements-test.txt
python -m pip install -r requirements-conda-test.txt
```

Some of this probably isn't necessary? But I like to have everything in my environment 🤓

**Describe the solution you'd like**

If we put a `[dev]` optional extra in `setup.cfg` a user can simply do `python -m pip install -e .[dev]` to get everything needed in one easy command.

This would look like:

```ini
[options.extras_require]
dev =
    <Contents of requirements files>
```

**Describe alternatives you've considered**

Just continue using my list of commands.

**Comment by cjolowicz** [comment]
You could achieve the same with a requirements-dev.txt, no? It can reference the others and perform an editable install of Nox. There is no need to change the package metadata this way.

**Comment by ktbarrett** [comment]
I actually like using nox for this.

```python
@nox.session(reuse_venv=True)
def dev(session):
    session.install("pytest", "black", "isort", "mypy")
    session.install("-e", ".")
    if session.posargs:
        session.run(*session.posargs, external=True)
```

Now you can use it.

```sh
nox -e dev  # builds the environment
. .nox/dev/bin/activate  # activates it
```

or...

```sh
nox -e dev -- bash
# you are now in your environment, only an "exit" away from cleanup
```

**Comment by FollowTheProcess** [comment]
@ktbarrett Check out the `dev` session in the [cookbook](https://nox.thea.codes/en/stable/cookbook.html#instant-dev-environment) it's very similar!

Coming back to this. Are we interested in a `requirements-dev.txt`? It's a pretty cheap thing for a small improvement in DX, but not a dealbreaker if not

**Comment by DiddiLeija** [comment]
I made #582 for adding a `requirements-dev.txt`.
