### ISSUE TITLE
Output capturing by session.run()

### ISSUE THREAD

**Issue by mat-rs** [theacodes/nox#572]
**How would this feature be useful?**
I need to handle some git commands during sessions, evaluating their output.
Currently it is possible to capture the output of processes executed by run() by setting silent=True.
However, this is not documented.

**Describe the solution you'd like**
It would be great if capturing output of run() would be made an official documented feature.
It would also be useful to capture output and exit code at the same time.

**Describe alternatives you've considered**
An alternative would be using subprocess instead of session.run()

**Comment by ktbarrett** [comment]
I have also run into this in the past. I think it should be documented.

**Comment by mat-rs** [comment]
Suggestion for https://github.com/theacodes/nox/blob/main/nox/sessions.py#L299
```
:param bool silent: Silence command output, unless the command fails.
            If ``silent=True``, ``run()`` will return the command's output on success.
            ``False`` by default.
```

**Comment by ktbarrett** [comment]
I'm wondering if this is actually a violation of separation of responsibilities. Perhaps there should be two options, `silent` which doesn't echo stdout, and `capture` which captures the stdout for processing by nox.

**Comment by mat-rs** [comment]
Good point.
I'm actually not entirely sure why ``run()`` doesn't simply always return the output, independent of ``silent``
It comes down to this line: https://github.com/theacodes/nox/blob/538aa6cae0d838817971064c939acee61eabd555/nox/command.py#L141

However, if the command fails, it raises an exception, so there is never a case where False is returned as far as I can see.

**Comment by FollowTheProcess** [comment]
Hmm. I'm hesitant to to add both a `capture` and a `silent` option as I think this adds unnecessary complexity (we'd have to handle mutual exclusivity etc.)

I agree we should document that if `silent = True` the command output is returned.

> I'm actually not entirely sure why run() doesn't simply always return the output, independent of silent

I'm on board with this, however I just spent 5 mins playing around with a local version and it seems if you just use `return output` it still only brings it back if silent is True which is confusing me slightly, I suspect it's something to do with `popen`. I'd have to have another look when I have a bit more time.

In the meantime if you want to take a crack at this in a PR it's always welcome!

FYI The maintainers are listed here: https://nox.thea.codes/en/stable/#maintainers-contributors

Feel free to ping any one of us, we can't guarantee a response time but we try our best!

**Comment by DiddiLeija** [comment]
> I agree we should document that if `silent = True` the command output is returned.

I agree. Adding a `capture` option will need a lot of discussion, starting with the fact that a lot of complexity would be added, and maybe we don't want that. However, a good paragraph in the docs can help the users.

I'll work on a PR to update the docs ;)

**Comment by ktbarrett** [comment]
> I'm on board with this, however I just spent 5 mins playing around with a local version and it seems if you just use `return output` it still only brings it back if silent is True which is confusing me slightly, I suspect it's something to do with `popen`. I'd have to have another look when I have a bit more time.

A quick look at the source code for `popen` shows that it only uses a PIPE for stdout if `silent is True`. Unfortunately I am not aware of TEE or something similar that could both let stdout of the process be printed and also capture it like PIPE does. So I'm not sure this is possible :disappointed:

**Comment by FollowTheProcess** [comment]
I think we _could_ probably change that and e.g. capture the output by default from `popen` and then anything that calls `popen` can decide whether to show the output or keep it hidden. But I'm not sure the effort is worth the reward? 99% of users will either want to show the output, or capture it and do something with it, not both. As long as users know that setting `silent = True` will capture the output (I actually didn't even know this and had been using `subprocess` for this purpose) I think we're in a good place 👍🏻 

I'm going to close this off but happy to reopen if we come up with anything else, thanks all!

**Comment by mat-rs** [comment]
Great, thanks guys! :)
