### ISSUE TITLE
Add setup.py stub to support editable installs

### ISSUE THREAD

**Issue by ktbarrett** [theacodes/nox#576]
**How would this feature be useful?**
Editable installs are very useful for development, but without the presence of a setup.py file `pip` refuses to install the project in editable mode.

**Describe the solution you'd like**
A simple stub for setup.py is sufficient to support editable installs since setup.cfg is used for all project description. See below for an example of what that sub would look like.

```python
from setuptools import setup


setup()
```

**Describe alternatives you've considered**
Manually installing nox after every change...

**Comment by FollowTheProcess** [comment]
You don't need a setup.py shim to do editable installs anymore!

Mine works as is:

![image](https://user-images.githubusercontent.com/62767721/154023541-9a6d739b-3469-4fb9-9064-6bc4d3b27ab3.png)

![image](https://user-images.githubusercontent.com/62767721/154023579-dac16e95-18cf-4b55-8022-f409a128ecea.png)
