### ISSUE TITLE
Use consistent spelling for Nox in documentation

### ISSUE THREAD

**Issue by cjolowicz** [theacodes/nox#579]
Currently, docstrings, option help texts, and rst files use various spellings for Nox and the noxfile.py:

- nox
- Nox
- noxfile
- nox file
- Noxfile

We should make these usages consistent. For Nox itself, the case is already quite clear:

- Nox is spelled with a capital N, as a general rule.
- As an exception to this rule, nox is spelled in lowercase when referring to the executable. (Use sparingly.)

For the noxfile.py file, I'd propose *Noxfile* with capital N, just to get the bikeshed going. Any preferences/thoughts?

**Update:** Looking at some more of @theacodes' original commits here, I believe that "Nox" and "Noxfile" are indeed the preferred usage.

**Comment by CN-M** [comment]
Hey. I'd like to give this one a shot as my first real contribution to open source.
So if I understand the issue properly:
nox -> Nox // Unless we're talking about the executable
noxfile/nox file -> Noxfile

**Comment by DiddiLeija** [comment]
Hey @CN-M, thanks for offering!

> So if I understand the issue properly:
> nox -> Nox // Unless we're talking about the executable
> noxfile/nox file -> Noxfile

As far as I know, this is our preferred spelling, at least with "Nox". However, I don't know about the "nox file" - "noxfile" - "Noxfile" spelling preference.

@theacodes Any thoughts about this?

**Comment by FollowTheProcess** [comment]
> Update: Looking at some more of @theacodes' original commits here, I believe that "Nox" and "Noxfile" are indeed the preferred usage.

Based on the above I think "Noxfile" is fine 🙂

**Comment by theacodes** [comment]
`Noxfile` is fine, although to be honest it's probably better if we use `noxfile.py` consistently instead.

**Comment by CN-M** [comment]
I'll just change the `nox` to `Nox` for now until a consensus is made about the `noxfile.py`

Although, the goal here is consistency in spelling and not necessarily to capitalize every instance of `noxfile`, so we could probably go either way as long as we keep consistent with our changes and consistent with how we refer to `noxfile` moving forward.
But I'm the new guy here so I'll get to work on this while I wait on you guys.

**Comment by CN-M** [comment]
Upon interacting with the code and making a few of the spelling changes, I think we should go along with what @theacodes said and use `noxfile.py`. So this is how I'll be implementing the changes so far and you guys will let me know if you want it done differently:
- `nox` to `Nox`.
- `nox` stays `nox` if it's an executable.
- `noxfile.py` stays `noxfile.py`.
- `noxfile` to `Noxfile` outside of the context of a file or executable.

**Comment by FollowTheProcess** [comment]
Sounds great to me 👍🏻
