### ISSUE TITLE
Add a list of projects using Nox to the documentation.

### ISSUE THREAD

**Issue by theacodes** [theacodes/nox#75]
- https://github.com/dhermes/bezier
- https://github.com/GoogleCloudPlatform/google-resumable-media-python

**Comment by dhermes** [comment]
https://github.com/dhermes/bezier

**Comment by pradyunsg** [comment]
Also the following may be added: :)

- https://github.com/pradyunsg/zazo
- https://github.com/pypa/python-packaging-user-guide/

**Comment by lukesneeringer** [comment]
https://github.com/googleapis/gapic-generator-python
