### ISSUE TITLE
Allow passing env to `session.install()`

### ISSUE THREAD

**Issue by dhermes** [theacodes/nox#79]
For example, if I want to build a C extension in "debug" mode, I have to swap

```python
session.install('.')
```

for

```python
session.run('pip', 'install', '--upgrade', '.', env={'DEBUG': 'True'})
```

For context, here are the current [`InstallCommand` constructor][1] and [`SessionConfig.install()`][2].

[1]: https://github.com/jonparrott/nox/blob/v0.18.2/nox/command.py#L163-L165
[2]: https://github.com/jonparrott/nox/blob/v0.18.2/nox/sessions.py#L195

**Comment by dhermes** [comment]
@theacodes @alanbato Might I "take over" PR #83 to fix this? Happy to send commits into it.

**Comment by alanbato** [comment]
Sure! I think I was having trouble getting the tests to pass. Good luck! :)

**Comment by theacodes** [comment]
Done in d7f4a0a
