### ISSUE TITLE
Allow nox sessions to run in parallel

### ISSUE THREAD

**Issue by tswast** [theacodes/nox#88]
In repos like python-docs-samples, there are a ton of samples in directories that don't depend on each other. It would be nice if there was a `parallel_parametrize` option or something to spin up some threads to run these sessions in parallel.

**Comment by jonparrott** [comment]
The biggest challenge here is dealing with output from running multiple sessions. We'd have to figure out some way to capture all of the output for the separate processes and print them in a sane way.

**Comment by jonparrott** [comment]
All *commands* in a session are spawned via subprocess, but the sessions themselves are not. That's a good approach though, we could leave most of the logic in place and just ensure each session gets its own subprocess.

**Comment by davidism** [comment]
I commented about this in detox (tox's solution for parallel testing): There should be a way to indicate that some tests should run sequentially before/after parallel tests. For example, tests for all interpreters should run in parallel, then a final "coverage collect" env can run to collect all the coverage data.

A possible solution to express this is a "group" session. It behaves like a normal session (runs sequentially with sessions defined next to it), but has it's own `session` decorator to register nested sessions (or more groups) that run in parallel when it runs.

**Comment by theacodes** [comment]
Yeah, with that we're getting into dependency graph territory (which makefiles honestly have a pretty reasonable solution to). I'm open to it, but we definitely need to be able to figure out how to capture output from the multiple runs without stomping.

**Comment by thedrow** [comment]
Now that I'm thinking about this, maybe we should make [invoke](http://www.pyinvoke.org/) a dependency.
It will make running processes so much easier and will allow us to offload some of the implementation to their project. This includes redirecting output and running processes in parallel using the `asynchronous` keyword argument of the [`run()`](http://docs.pyinvoke.org/en/stable/api/runners.html#invoke.runners.Runner.run) method.
It's quite the refactor though.

Using invoke will also help resolve #198.

**Comment by staticdev** [comment]
tox have -p option (which works ok), how about using the same approach for output instead of reinventing the wheel?

**Comment by theacodes** [comment]
Closed in favor of #198

**Comment by davidism** [comment]
I'm not sure if #198 would solve this, unless the intention is that one nox session could call a bunch of other nox sessions as background tasks. That would still require the author of the session function to handle detecting when the task was finished and handling parallel output and reporting. Could you clarify how #198 will enable parallel sessions?

**Comment by staticdev** [comment]
@davidism might be better to ask there since they already closed this issue.
