### ISSUE TITLE
Support/Bug: nox not creating virtualenv

### ISSUE THREAD

**Issue by pradyunsg** [theacodes/nox#90]
```py
import nox


@nox.session
def hello(session):
    session.interpreter = "python2.7"

    session.run("python3", "-m", "flit", "build")
    files = glob.glob("./dist/*.whl")
    if not files:
        session.error("Could not find any built wheels.")
    session.install(*files)
    session.install("-r", "tools/reqs/test.txt")

    session.run("pytest", *session.posargs)
```

Somehow, the above script results in nox not even building a virtualenv.

```
$ nox -s hello
nox > Running session hello
nox > Could not find any built wheels.
nox > Session hello aborted.
```

If nox is composing the list of commands before actually executing them, it would result in an empty call to `install`. Here, however, it isn't even creating the virtual environment.

---

Honestly, I'm not sure what's happening here. If I comment out the second `install` line, somehow nox executes the session, but with `-r tools/reqs/test.txt`, which is exactly what was commented out. :/

**Comment by pradyunsg** [comment]
FWIW: I'm working around this by changing the run for flit, to call out a subprocess directly.

**Comment by theacodes** [comment]
Yeah, this is actually due to a quirk in Nox's behavior that was inherited from Tox: Nox is declarative. The commands are all collected before running - but that also means any non `session.{thing}` code is run immediately. Nox creates the virtualenv *after* collecting everything.

I honestly want to switch Nox to being imperative like Invoke. I don't think this would break any Nox scripts that I'm aware of.

**Comment by pradyunsg** [comment]
> Honestly, I'm not sure what's happening here. If I comment out the second install line, somehow nox executes the session, but with -r tools/reqs/test.txt, which is exactly what was commented out. :/

Any clue why this might be happening?

**Comment by theacodes** [comment]
No idea on that. Nox doesn't keep a cache of commands or anything- so if it's commented out I have no idea where that came from.

**Comment by dhermes** [comment]
FWIW I've worked around this by doing something like the following:

```python
def foo(session):
    files = glob.glob("./dist/*.whl")
    if not files:
        session.error("Could not find any built wheels.")

@nox.session
def hello(session):
    session.run(foo)
```

**Comment by pradyunsg** [comment]
Closing in favor of #91 + workaround being used. :)
