### ISSUE TITLE
Add `.nox` to GitHub's .gitignore

### ISSUE THREAD

**Issue by amitsaha** [theacodes/nox#92]
Thank you for `nox`. I made a [PR](https://github.com/amitsaha/gitignore/pull/1) to add `.nox` to GitHub's `.gitignore` file. But, I couldn't find a place in the documentation where it talks about it. Is that correct? if so, would a PR be welcome?

**Comment by theacodes** [comment]
Thanks for doing this! The `.nox` directory is documented here: http://nox.readthedocs.io/en/latest/usage.html#storing-virtualenvs-in-a-different-directory

Let me know if you need anything else.
