### ISSUE TITLE
When a Python version isn't installed, nox fails (without going on to the next session)

### ISSUE THREAD

**Issue by pfmoore** [theacodes/nox#93]
I have a `nox.py` file for testing my project, and I want to specify all of the Python versions I support. That's easy enough, and works fine for CI. But when running nox on my local PC, I don't have all those Python versions installed. As a result, I get `RuntimeError: Unable to locate Python interpreter "python3.5".` when I run plain `nox`, and the run stops there.

Two things would be a huge improvement:

1. Respect the `--stop-on-first-error` setting, and by default skip sessions that can't be created because the Python interpreter isn't installed.
2. Avoid the ugly traceback, and simply print an error "Python interpreter XXX not installed - skipping".

Manually specifying just the environments I want to run isn't really practical (apart from anything else, the syntax for specifying a parametrised environment is much more verbose than tox's `-e py36`).

**Comment by theacodes** [comment]
This is a great idea, and should be pretty easy to do. I'm cool with both 1 and 2.

**Comment by theacodes** [comment]
Seems that making Nox imperative fixed this. :)

What it looks like now:

<img width="1132" alt="screen shot 2018-08-23 at 8 00 13 pm" src="https://user-images.githubusercontent.com/250995/44562624-3af0ae80-a70f-11e8-87df-a325c03f6908.png">

Let me know if there's more I can do here, @pfmoore!
