### ISSUE TITLE
Add ability to customize session name for parametrized tests

### ISSUE THREAD

**Issue by theacodes** [theacodes/nox#96]
https://docs.pytest.org/en/latest/example/parametrize.html#different-options-for-test-ids

**Comment by theacodes** [comment]
Original context: https://github.com/theacodes/nox/pull/94#discussion_r205984376

**Comment by tseaver** [comment]
I *really* hate the hashing bit.  Since I contributed the original `session.virtualenv_name` bit removed in #94, I'd really like to see its replacement.

**Comment by theacodes** [comment]
The hashing usually only happens if Nox detects the virtualenv name will cause issues with `exec`, changing the name to get around that will probably lead to weird errors.

**Comment by theacodes** [comment]
Basically, that is to say - I may allow changing the parametrized session name and that will *indirectly* translate into changing the virtualenv directory name, but it hashing will still occur if the path is too long.

**Comment by tseaver** [comment]
The heuristic you are using to decide "problematic" length is unhappily conservative for me:  max shebang length is 128 on my system, which is pretty standard for Linux.

**Comment by theacodes** [comment]
It's conservative because both the path to python and the path to any tools must be less than the shebang length, so we try to catch issues early instead of having users run into weird "not found" errors.

**Comment by tseaver** [comment]
The issue with the hashed name is the lack of discoverability when a failure occurs.  Maybe for hashed environments, `nox` could create symlinks to the hashed directory using the un-hashed name?

**Comment by dhermes** [comment]
1. This discussion seems to be different than the original goal of this issue.
1. I think the root of @tseaver issue is that he wants to jump into the virtual env when necessary. This could be done by adding seem features to the `nox` CLI.

**Comment by theacodes** [comment]
Breakpointing might be a good candidate for your use case, then.
