### ISSUE TITLE
Add `needs_nox` parsing to specify minimum version

### ISSUE THREAD

**Issue by dhermes** [theacodes/nox#99]
The current switch from `0.19.1` to `>= 2018` will probably cause some breakage and it may be useful to specify

```python
needs_nox = "2018.7.31"
```

much in the same way Sphinx supports a

```python
needs_sphinx = "1.0"
```

**Comment by theacodes** [comment]
Where does `needs_nox` need to go?

**Comment by dhermes** [comment]
In `nox.py`; `needs_sphinx` goes in `docs/conf.py`. (Maybe `NEEDS_NOX` to be PEP8 friendly?)

**Comment by theacodes** [comment]
Interesting. What would be our behavior if the version wasn't satisfied?

(Also, keep in mind I'm planning on `s/nox.py/noxfile.py` so we can support `python -m nox`).

**Comment by dhermes** [comment]
> What would be our behavior if the version wasn't satisfied?

Similar to what Sphinx does? At c64cc8e43ca41ef1e9eae71073f0b696538e3dc3, the diff

```diff
diff --git a/docs/conf.py b/docs/conf.py
index ab3d6ac..bd8d482 100644
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -28,7 +28,7 @@ sys.path.insert(0, os.path.abspath('.'))
 # -- General configuration ------------------------------------------------
 
 # If your documentation needs a minimal Sphinx version, state it here.
-#needs_sphinx = '1.0'
+needs_sphinx = '1.8.0'
 
 # Add any Sphinx extension module names here, as strings. They can be
 # extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
```

yields the following

```
$ nox -s docs
...
nox > cd docs
nox > sphinx-build -b html -d _build/doctrees . _build/html
Running Sphinx v1.6.2
making output directory...

Sphinx version error:
This project needs at least Sphinx v1.8.0 and therefore cannot be built with this version.
nox > Command sphinx-build -b html -d _build/doctrees . _build/html failed with exit code 1
nox > Session docs failed.
```

> (Also, keep in mind I'm planning on `s/nox.py/noxfile.py` so we can support `python -m nox`).

Yay!

**Comment by theacodes** [comment]
Sounds reasonable.

**Comment by cjolowicz** [comment]
I'd be interested in picking this up.

**Comment by theacodes** [comment]
Go for it.
